### ISSUE TITLE
Adjust html downloads page table

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#10]
> Only thing I am not sure about is the icons--they are a little busy. Perhaps removing even just one of the three icons across the row and changing the weight of the document title would be enough to make it more legible. On the backend we might shuffle around the way the CSS etc. works, but I think we can easily adjust that without breaking code that runs through the wizard.

We can possibly use bootstrap classes to take care of some of these pain points instead of making our own css. That will come with advantages like a dark theme, etc. if that's something da can offer. [Sorry that didn't occur to me sooner.]

**Comment by nonprofittechy** [comment]
I have a version with some very small tweaks that is in my playground (e.g., adding emphasis and removing the file icon). Will commit it soon. It should be ready to play around with a different method of styling soon.

**Comment by nonprofittechy** [comment]
See https://github.com/SuffolkLITLab/docassemble-AssemblyLine/commit/3611febcced1ca17bb7443534c484490948a524f. I fleshed out the API a bit, added some possible keyword parameters and put in some suggested refactoring, but I think it's ready for any CSS work that @plocket wants to do.

**Comment by nonprofittechy** [comment]
Addressed in #26 

We may still want to revisit appearance when their are multiple documents
