### ISSUE TITLE
move the address_fields method to the `ALAddress` object

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#101]
We can keep `address_fields` on the `ALIndividual` class, but it can reference the `ALAddress` one. This will let us use it for more kinds of address objects, like the `other_addresses` attribute on the 209A form.

**Comment by nonprofittechy** [comment]
We also need to change the `ql_baseline.yml` file to point to the right attributes.

**Comment by plocket** [comment]
Closed by #102?
