### ISSUE TITLE
Figure out a standard way to expose a way to review all of the forms when a package assembles multiple forms in separate packages

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#103]
This could also require changes in the Weaver, but people often don't have a way to tell the Weaver multiple forms will be included at that point.

**Comment by nonprofittechy** [comment]
One of the things to consider is that someone might think they could edit the name separately, but actually there is one `users` object that is used to complete all of the forms.

**Comment by nonprofittechy** [comment]
For now: just have the developer of the "umbrella" interview copy/paste the review blocks from the sub-forms.

**Comment by nonprofittechy** [comment]
Another thought: we may want to add an "edit" button for each row that takes you to the review screen for that specific form.

**Comment by plocket** [comment]
Does multiple documents refer to multiple YAML files?

**Comment by nonprofittechy** [comment]
Related: #209

**Comment by nonprofittechy** [comment]
I implemented this behavior in https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/. I am not positive it needs to be standardized, but it feels like we have most of the elements to standardize it in place already. Adding something to the interview_metadata could be the only solution we need.

**Comment by nonprofittechy** [comment]
I think enough of this is in the fix to #209 that this is no longer appropriate. On balance, using the section links to edit answers is cumbersome and an overall review screen is more compatible with a mobile device, so adding a big feature for this doesn't make much sense. But #209 makes this possible if an author wants this behavior.
