### ISSUE TITLE
Anywhere that we say "you" we should consider how to account for forms that are always used by an attorney

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#109]
This should be easily solvable by using `set_info()` https://docassemble.org/docs/functions.html#set_info

**Comment by nonprofittechy** [comment]
The easy part is rewriting the text. The hard part is figuring out the standard.

**Comment by nonprofittechy** [comment]
This is a live issue with the https://github.com/SuffolkLITLab/docassemble-IlFeeWaiver form where you can file on behalf of someone else.

I think there are two separate issues:

1. Make all of the questions that say "you" responsive to the value of `get_info('user')`. Set a default for that.
2. Come up with a new standard variable name to represent the person filling in the form. In ILFeeWaiver, we are using the variable "signer" which I think works pretty well but I can imagine a lot of forms where the variable name will get re-used for a different meaning. Maybe something long like "question_respondent", "person_answering_interview", "form_filler", or just "interview_user" or perhaps prefixed "al_interview_user" to indicate it's about the interview, not the actual document is best.

I think we can safely start refactoring the ql_baseline questions but we should also make sure to update all of the translations that we now have into various languages so those aren't instantly broken.

**Comment by BryceStevenWilley** [comment]
> Make all of the questions that say "you" responsive to the value of get_info('user'). Set a default for that.

So I understand how we would be using `set_info`, to solve 1, we would have to:
* remove the questions that specifically use `users[0]` as the target object
* use the object methods for other ALIndividual questions, i.e. instead of ["What is ${ users[i] }'s address"](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/f4c74de8dcc945e323ce1eb8089fd907269fe432/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L479), we'd do:
  ```mako
  What is ${ users[i].possesive('address') }?
  ```
* call `set_info` early in the interview if and only if the user says they're filling it out for themselves (this is also 3, right? just the variable to store that question in?)

>  Set a default for that.

I'm not sure what you mean there. Is it the default for if the user is the person answering questions (i.e. true or false)? That should be what we've been assuming in the current interviews, that `users[0]` is the person answering questions, right?

**Comment by nonprofittechy** [comment]
I don't think we'd need to re-target any existing questions, just change the dynamic language, but it's worth figuring out the clearest/least disruptive change.

`users[0]` would always hold the name of the person whose information goes on the forms first (the actor). We would just be tracking whether we should be using direct address for that person, or referring them by their role name.

My expectation is that it would look like this:

```
question: |
  % if get_info("user") == users[0]:
  What is your name?
  % else:
  What is the plaintiff's name?
  % endif
fields:
  - code: users[0].name_fields()
 ```

**Comment by nonprofittechy** [comment]
Thoughts:

- Make sure this is backwards compatible
- Will need to think about two "intermediate" variables that might get mis-used
    - It might need to run in an initial block. Can we make that overridable by referring a second code block?
    - Whatever variable we use to answer the question "Are you the tenant or the attorney?"

**Comment by nonprofittechy** [comment]
Note that we can avoid an intermediate value if we use `buttons`--you can run a simple Python expression in a button. But are buttons as usable as other questions?

![image](https://user-images.githubusercontent.com/7645641/187245711-87e670f7-1b42-47f7-8e4e-a5e1c08ad34b.png)

![image](https://user-images.githubusercontent.com/7645641/187245737-f0704fe7-a47c-4db0-b65e-e400f805ee12.png)

**Comment by nonprofittechy** [comment]
New variable names:

- `al_person_answering`
- `al_set_person_answering`

**Comment by nonprofittechy** [comment]
I've done this in a few interviews, in an approximately standardized way. See https://github.com/LemmaLegalConsulting/docassemble-HousingCodeChecklist/blob/f9dae1abdce0e65530684f78dee86c06c65eafcd/docassemble/HousingCodeChecklist/data/questions/customized_screens.yml#L13

Perhaps we call it `al_person_answering` and default with a code block to "user". Then we can provide instructions and a sample question to ask the user. The noun would almost always be customized so we may not need to provide a question that goes along with the logic, except as a sample.

**Comment by nonprofittechy** [comment]
Question to figure out I guess: do we test against the string `"user"` or object identity with `users[0]`
