### ISSUE TITLE
Email documents UI

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#11]
Transfer email capabilities from https://github.com/SuffolkLITLab/docassemble-ALDocument/tree/email_docs with some adjustments. As an alternative to needing to include a `.yml` file with an event block in it:

> If you would like an HTML button to run Python code, how are you able to abstract that?
> This is for triggering an action on a custom object. Specifically, sending an email with the contents of that object.
> It looks like with `action_perform()` and `url_action()`, docassemble will look for the definition of an event. I'd like the event to be enclosed in the module itself, so an interview author can use the code without having to include a YAML file or to write their own email-sending event.
> something like:
> ```yml
> subquestion: |
>   ${ my_docs.send_email_button() }
> ```
> to run the send_email() function in the module itself.
> Can an event be defined in a module? Weird question since iirc the event itself is never defined. Alternatively: is there a way to trigger an action that is not a docassemble `event` via JavaScript?
> Maybe by using `@property` on a method in the class definition

☝️  Confirmed

> whatever method you currently have of sending data to an event block in YAML could similarly be used in a method of the object. the `@property` decorator makes the method look like an attribute to outside code that interacts with it.
you might have seen that pattern to use a function to define the complete attribute of an object for a list

> Search for `@property` at https://docassemble.org/docs/groups.html

The javascript that listens for the event and detects the state of the checkbox and the value of the input
> will need to be either part of the HTML, or a JS dependency. i assume that would be handled by an interview-wide JS dependency

**Comment by nonprofittechy** [comment]
Basic scope of this feature will be:

1. A method on the ALDocumentBundle class that creates an HTML button to send the bundle by email. Something like: `my_docs.send_email_button_html()`
2. Moderate flexibility that is handled by optional keyword parameters to the method.
3. External JS dependency is OK. External CSS dependency is OK.
4. Avoid asking the user to do anything inside the YAML itself other than including JS and CSS which can be used for the whole project (e.g., courtformsononline.org or equivalent in a different state)--should never need customization on a per-interview basis.

**Comment by nonprofittechy** [comment]
Fixed in #26
