### ISSUE TITLE
Add a question to handle detailed user role

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#111]
Some forms can be used for plaintiff/petition/appellant and the role needs to be specified on the form.

We can write a question to handle this very common need.

**Comment by nonprofittechy** [comment]
This could possibly be linked to the weaver. I would say about 10% of forms need the detailed label for the person starting/responding to the case--general motion type forms that can be used in multiple kinds of proceedings.

**Comment by BryceStevenWilley** [comment]
Related to https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/317 in the weaver.
