### ISSUE TITLE
Need to create a function that simulates `skip undefined: True`

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#118]
A lot of interviews may depend on `skip undefined: True` to operate correctly. However, this does not work if we pass the list of fields as code.

It could be helpful to write a function that treats the YAML as just a plain YAML block and processes the mako with the option that skips variables that are not defined. This is a built-in capability of Mako. It looks like Docassemble simulates that behavior by trapping exceptions. (see https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/parse.py#L5177 which is for a review block--haven't found exact one for processing attachment but I assume it is similar)

**Comment by purplesky2016** [comment]
Is this what you are looking for, it's for attachment: https://github.com/jhpyle/docassemble/blob/bf21ebbd880c39bf1a4f3b90fbdd9ed06516f79e/docassemble_base/docassemble/base/parse.py#L4761

**Comment by nonprofittechy** [comment]
See #53 for motivation

**Comment by nonprofittechy** [comment]
This is too specific a solution for a still pretty abstract problem--how to save reusable data from a form.
