### ISSUE TITLE
ALDocument.send_button_html() does not close all elements properly

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#119]
The ALDocument.send_button_html() method captures any text you put after it.

![image](https://user-images.githubusercontent.com/7645641/116818608-4cceb480-ab3a-11eb-99d6-eece0841747a.png)

Looking closely at the HTML, it appears all of the elements are properly closed. It might just be an issue with the Mako parser.

**Comment by purplesky2016** [comment]
When I worked on #65, I noticed a missing `</td>` in `def table_row` and added it.
