### ISSUE TITLE
Create dummy user instructions page that works w/o our custom courts object

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#12]
This is mostly helpful for the al_question_test.yml file, but it should also be a good model of how this template will work.

In practice, we want the wizard to create a template of the next steps instruction file. https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/98

**Comment by nonprofittechy** [comment]
This means adding a next_steps.docx file to the download screen in al_question_test.yml, just so it's a sample that shows how to use the feature even if you don't use the weaver to generate your interview.

**Comment by purplesky2016** [comment]
Tried to add one of the simpler ones `next_steps_other.docx`, but it still contains `interview_metadata['title'] `and 
`interview_short_title`, both are generated by the Weaver. Do we really want to add this file?

**Comment by nonprofittechy** [comment]
Because this would only be a demonstration, and couldn't be used as a real "next steps" document in a real filing, this feels like an issue to skip.
