### ISSUE TITLE
ALDocument: Send email button does not send email when sending non-editable documents

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#120]
**Describe the bug**
When using the below code, the 'Send' button does not send an email:
```
${ al_user_bundle.send_button_html(show_editable_checkbox=False) }
```

**Additional context**
This bug was reported by a different user, but it makes sense. From what I can see, I expect there is an error in the browser console. Probably that you can't get `checked` or `[0]` of undefined. The code that generates the html for the document sending elements leaves out the checkbox if the developer does not want to show it. That means this line will error:
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/4dd5e94e1ee256527ace6b8f7c799a5e81712d99/docassemble/AssemblyLine/data/static/aldocument.js#L7

I can see two ways to handle this.
1. Check for the existence of the checkbox before getting its `checked` value.
2. Don't leave the element out, just disable and hide it.

Thoughts on approaches?

**Comment by BryceStevenWilley** [comment]
You spot on about the error, here's a reproduction of the error:
```
Uncaught TypeError: $(...)[0] is undefined
    aldocument_send_action https://apps-dev.suffolklitlab.org/packagestatic/docassemble.AssemblyLine/aldocument.js?v=2.0.15.1:7
    <anonymous> javascript:aldocument_send_action('al_user_bundle.send_email_action_event','al_wants_editable_al_user_bundle','al_doc_email_al_user_bundle'):1

Uncaught TypeError: $(...)[0] is undefined
    aldocument_send_action aldocument.js:7
    <anonymous> interview:1
    daEmbeddedJs interview:1623
    dispatch utf8.js:203
    handle utf8.js:203
 ```

**Comment by plocket** [comment]
For now I went with option 1, though I'm not convinced it's the best option. It's just faster for me at this time in my life - for option 2 I need to look into what other attributes need to be set to disable the checkbox appropriately and accessibly.
