### ISSUE TITLE
Global Exception / Error catch to show to user

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#121]
There have been a few bugs that pop up where Javascript silently fails, making some part of the page fail. Examples include:
* The Google geocoding not working when it should
* Datatype javascript being run on [every single interview page server wide](https://github.com/SuffolkLITLab/docassemble-scdao/commit/b35c775f14f8be006d5508ff8e8616ce1f13161a#diff-7122eba83522ae1ae7a1e472c2e97e9984bf7be374277b76eea18895ae903c85R10-R25)
* The new audio component not working on the help page: #68
* The send email button not working when "send editable copy" isn't present: #120 

Some of these fail gracefully, just losing aesthetics or helpful but not necessary functionality. In other cases, (specifically #120), actual functionality just silently doesn't work. Leaving users confused.

Is there some way of adding a global try-catch in Javascript, that would catch all Errors / exceptions that eventually spit out to the console, and show the user a "something went wrong! You can continue or send us feedback" that links directly to the feedback page?

**Comment by plocket** [comment]
If we wanted something general that would act like the alerts that come from the server, it would at least take some js fiddling of its own, but it might be doable.

Possibly helpful reference material:
- https://stackoverflow.com/a/20534588/14144258
- https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by BryceStevenWilley** [comment]
Had a discussion about this being a global solution vs an individual solution (per function), and then if it's individual, we need to find which functions that we need wrap. We landed on the global solution being nice but technically tricky and fragile, so next steps would be to just triage individual functionalities and add try-catches to them as feasible.

**Comment by nonprofittechy** [comment]
Just bumping this. Is this really realistic or scoped enough to be an issue? @BryceStevenWilley please close if not. The original description, a "global try/catch" sounds a bit unrealistic given how little control we have over various JS that Docassemble emits. It wouldn't be a very safe option.

**Comment by BryceStevenWilley** [comment]
As mentioned in https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/121#issuecomment-831419575, the global solution isn't what we thought we would progress with. I haven't seen many JS bugs since this PR, and I guess it's just a downside of JS in the browser. I'll close.
