### ISSUE TITLE
Set up release notifications

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#122]
The discussion, iirc, concluded that we would set up github release tags and people could subscribe to those. Possibly a bot somewhere in there. Docassemble's core library itself was described as a good model for this.

**Comment by BryceStevenWilley** [comment]
Todo for this issue:

- [ ] integrate bumpversion to change version strings, tag, and commit (#141)
- [ ] Update the Pypi repo
- [ ] Update a change log
  - [ ] Force manual messages on minor or major releases to summarize what's changed.
- [ ] integrate with a Teams announcement

**Comment by BryceStevenWilley** [comment]
Reopening, was not reliable with different github commits on the remote and some Pypi issues. Going to squash some more bugs here, and close this issue when we've been using it for a while.
