### ISSUE TITLE
ALDocument: Add sending editable PDF in email

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#123]

**Comment by nonprofittechy** [comment]
I think this is a good idea. To clarify right now though, the PDF is always the editable PDF unless the interview author set `editable: False` in the attachment block. See: https://docassemble.org/docs/documents.html#editable (the default is for a PDF to remain editable).

Right now, the Weaver does not set this modifier on the attachment block at all. We could use Mako to make the value contingent, probably by using a different key for attachment. It would require editing the Weaver and all generated code.

We could alternatively create a flattened version of the PDF for normal sending by email using a post-processing step in the ALDocument class. But that would not allow us to retrieve the editable version if the interview author had modified the attachment block.

Given overlapping goals--making this a global behavior set at the class or AssembleLine package level, allowing the interview user to select a different choice, and allowing the interview author to set some custom behavior, the issue for this is really just where we value the flexibility and how much existing code we are willing to require to adapt to work with the new behavior we come up with.

**Comment by plocket** [comment]
Just to describe one possibility in other words:

If the developer set their PDF to be editable they could use ALDocument to send a flattened version of the PDF or an editable version. That would add to processing time for flattening editable PDFs and has the potential to slow things down prohibitively.

**Comment by plocket** [comment]
Has this been handled with the "include editable" checkbox? There might be a nuance I've forgotten.

**Comment by nonprofittechy** [comment]
Going to close this for now as not actionable--we always send the editable PDF and we don't have any code in the Weaver to change that default. Can revisit with the thoughts on this thread later though!
