### ISSUE TITLE
Add way for someone to tell us they do not have an address

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#127]
This is linked to providing a method of collecting international addresses

**Comment by nonprofittechy** [comment]
What we are thinking of here is that it will be hard for us to validate and UX test. But we might just try it and experiment with it so people can give us feedback on the feature.

It should be very basic--it will let people say "I don't have an address" and let them write in something else.

We need to let people output that too. So: override the address.address attribute, and the address.full() method.

**Comment by plocket** [comment]
One way to possibly avoid rewriting all the `address` methods is to give values to each `address` attribute. For example, with 'N/A'

**Comment by purplesky2016** [comment]
I guess this can get complicated in real life:

1. Homeless but has a po box to receive mail.
2. Homeless and live in friends/relative's house, currently use their address for mail.
3. Live in a shelter and can use their address.
4. Live in streets and can use local church etc to receive mail.

The bottom line question may really be whether or not the person has an address to use for mail. In that case it's more of an issue to label the address input appropriately, except for po box. Is po box an acceptable input?

**Comment by nonprofittechy** [comment]
Good point about a PO box. I think that will fit in the standard address field but we should make sure
