### ISSUE TITLE
Add some strategic color

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#131]
Our pages are still very stolid. It's been shown that adding images/cartoons/graphics has a big impact on users' comfort with using online tools. I would like to have a stronger visual identity for our forms.

One solution is to add some images from: https://www.flaticon.com/

**Comment by purplesky2016** [comment]
This should be considered together with #159. Need to discuss the scope.

**Comment by nonprofittechy** [comment]
This has been open for 2 years - going to close for now
