### ISSUE TITLE
Reduce width of datatype: integer fields?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#134]
Input width is an important clue for the type and length of input people are going to provide. It could be worth customizing the style of the integer input so it is a reasonable width for common number inputs. E.g., we usually use this for list gathering, where the reasonable width is only maybe 4 ems.

**Comment by purplesky2016** [comment]
Both `Integer `and `Number `datatypes share the same attribute `type=number`, so I used 10rem in case the input for Number is a large one. It also looks better in mobile than 4rem.

**Desktop**
![image](https://user-images.githubusercontent.com/20231649/117696996-fa237700-b18f-11eb-9905-2d4e299f69ff.png)

**Mobile** 
![image](https://user-images.githubusercontent.com/20231649/117697077-0f98a100-b190-11eb-82b5-0c5e1f466231.png)

**Comment by nonprofittechy** [comment]
I think this looks ready for a PR
