### ISSUE TITLE
Make `has_addendum` an optional attribute, and use `hasattr` to check its existence

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#138]
Just to remove one of the required attributes at class instantiation time

**Comment by plocket** [comment]
If we are just going to check for its existence which will avoid triggering an error that would require the developer to set it, why avoid giving it a default value?

**Comment by plocket** [comment]
I think I misunderstood how to set defaults in Python.
