### ISSUE TITLE
Create a demo YAML file that shows to use a user cover page and a court cover page

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#14]

**Comment by nonprofittechy** [comment]
Resolve #13 and #12 first

**Comment by nonprofittechy** [comment]
Also see: https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/156

**Comment by plocket** [comment]
Item for discussion: Pros and cons of keeping this in the documentation vs. in this repository.

**Comment by nonprofittechy** [comment]
This doesn't seem so relevant now that we're not actively working on email to court functionality.
