### ISSUE TITLE
Point logo to a file in AssemblyLine, not MAVC

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#152]
Currently the logo looks like this in `al_visual.yml`:

```html
  logo: |
    <img src="/packagestatic/docassemble.MAVirtualCourt/mass_icon.png" class="ma_icon" alt="MA State Icon"><div class="title">CourtFormsOnline: MassAccess</div>

```

We need to add a new logo and point it to AssemblyLine instead.

**Comment by purplesky2016** [comment]
If you attach the new logo image file here, I'll work on this issue.

**Comment by nonprofittechy** [comment]
Let's discuss today. Do we want a new logo? Stick with the Massachusetts logo? It doesn't have to be a great design for now, just something that works as a placeholder.

**Comment by nonprofittechy** [comment]
Here is what we use for ALGenericJurisdiction: note it is transparent which looks weird w/ default navbar color.

https://github.com/SuffolkLITLab/docassemble-ALGenericJurisdiction/blob/main/docassemble/ALGenericJurisdiction/data/static/iconmonstr-script-5-64.png

**Comment by nonprofittechy** [comment]
Double-check the license restrictions.

**Comment by BryceStevenWilley** [comment]
License on https://iconmonstr.com/license/ is relatively restrictive (can't use as a logo), and I tried to search a bit, but a lot of icons and logos require attribution on the viewable page itself, not just in the github or something. I drafted this SVG quickly, let me know if it works for our purposes.


![bryce_form_icon](https://user-images.githubusercontent.com/6252212/118522803-7aa32400-b70a-11eb-877e-a2bb47c320a5.png)

**Comment by nonprofittechy** [comment]
This logo looks fine to me

**Comment by purplesky2016** [comment]
Desktop
![image](https://user-images.githubusercontent.com/20231649/118533500-269e3c80-b716-11eb-9d84-d4aadb3019ea.png)

Mobile
![image](https://user-images.githubusercontent.com/20231649/118533681-5b11f880-b716-11eb-99d8-519c421e8f7f.png)

Lighter theme
![image](https://user-images.githubusercontent.com/20231649/118533966-b3e19100-b716-11eb-8ffe-81049ffc8bf7.png)

**Comment by nonprofittechy** [comment]
Be careful of changing the navbar height--it led to bugs in the past. We could rotate the logo or reduce the size as long as it is still legible.

**Comment by BryceStevenWilley** [comment]
Does it need to be square? It's getting squished for some reason. Here's a square one. 

![bryce_form_icon](https://user-images.githubusercontent.com/6252212/118534688-834e2700-b717-11eb-9b88-f59164f41e9b.png)


And agreed with Quinten, I can play around with the size to make the nav bar smaller.

**Comment by purplesky2016** [comment]
Oh, I was testing in my sandbox not in AL, just to see how the colors would play out. Its image style is `style="height: 60px; width: 40px;"`

What are the desired dimentions?

**Comment by nonprofittechy** [comment]
No specific dimensions in mind, but it will be easier if it doesn't require changing navbar height. I would look at the existing CSS as a guide--if it can just use that, we know it works with spacing for the escape button, etc.

**Comment by purplesky2016** [comment]
In that case, I'll use the current logo's dimension as the base, 
![image](https://user-images.githubusercontent.com/20231649/118536647-f9538d80-b719-11eb-92e6-c14d1ec31761.png)

and keep the height to be 40 px. 
![image](https://user-images.githubusercontent.com/20231649/118537454-f4430e00-b71a-11eb-9617-1385f115b0ba.png)

The style is defined in the logo's `set_parts`, not related to styles.css.
