### ISSUE TITLE
Handle new value: interview.typical_role='na'

### ISSUE THREAD

**Issue by purplesky2016** [SuffolkLITLab/docassemble-AssemblyLine#157]
Weaver issue https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/317 added a "na" value to `interview.typical_role`, which mostly covers non-court forms. We need to handle this new value in AL accordingly.

**Comment by purplesky2016** [comment]
I copied @nonprofittechy's comments for https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/317 here for easier reference.

> Let's just be careful to look for every place that user_role and user_ask_role are referenced. It's probably best to to directly use user_started_case if that's more appropriate, and to not force the interview to ask for user_role unless it is really needed.
> 
> Just doing a search in ql_baseline.yml is probably sufficient.

As I did the search, I found `user_ask_role ` rely on `al_form_type`, so I want to use` interview.form_type = 'non_court'` to handle `interview.typical_role='na' `. 

However, I can't find `interview.form_type = 'non_court' ` in master branch; I had it in https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/commit/19af952069b3be0b6496af6b71ff878b82f6a410. I am so confused.

**Comment by purplesky2016** [comment]
Also, as this issue is related to #111, I'll wait until that one is resolved.

**Comment by nonprofittechy** [comment]
No longer needed because we re-mapped existing form types instead of adding a new type "non_court"
