### ISSUE TITLE
Create some color panels that can be used on various pages

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#159]
Bootstrap has a few ways to add boxes on a page, which add some visual separation and interest. It would be nice if we could use those, but Docassemble seems to override them with the .dabody class. E.g., on this page: 
![image](https://user-images.githubusercontent.com/7645641/118677221-15af0300-b7ca-11eb-82ab-aa9023b029ce.png)

It would be nice to have a colored box around the author and copyright information just to break up the page a little bit.

Here is what I tried so far: bootstrap `panel` class, which just stayed the same color as the rest of the `body` element with no separation.

**Comment by purplesky2016** [comment]
We could create our own colored "panel-frame" classes with css rules that we want, e.g. border styles, background colors etc. Then any text using such classes would get the effects.

**Comment by nonprofittechy** [comment]
Also consider the collapse_template method here:

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/master/docassemble/ALToolbox/misc.py#L69

this creates a bootstrap of class `collapsed` which defaults to a light grey background. we might want that to be more colorful.

**Comment by plocket** [comment]
In what way did you add the `panel` class? I suspect we can find a css way to change that color.

**Comment by purplesky2016** [comment]
Example:
In styles.css:
```
.panel-frame1 {
  whatever ....
}
```

In the interview:
```
question: |
  <span class='.panel-frame1'>I want this text to have the .panel-frame1 styles</span>
```

**Comment by nonprofittechy** [comment]
Here is the Bootstrap example I tried: https://www.w3schools.com/bootstrap/bootstrap_panels.asp

As I said, the issue seems to be that the .da-body class overrides it. I'm sure we could fix it. This issue is to do just that.

We might want to do something like `collapse-template` where the info panel's contents come from a template and we have a function that applies the correct classes to the info panel's title and body.

**Comment by plocket** [comment]
It looks like support for panels has been dropped from Bootstrap4: https://getbootstrap.com/docs/4.0/migration/#panels. It looks like cards are where it's at. Here are some cards with backgrounds: https://getbootstrap.com/docs/4.0/components/card/#background-and-color. When I tried `.card`, it seemed to collapse the spacing between `subquestion` and `fields`, so we may have to refine the styles a bit.

We can still put `card` in a function if we think it would be helpful, though we might want to see how often we end up using this pattern before we make a function for it. I think https://docassemble.org/docs/recipes.html#progressive%20disclosure is the example to which you're referring?

As for what classes to use, I suggest we stick with bootstrap classes and themes. That way, developers (current or future) can more easily develop all the styles of an interview together.

**Comment by purplesky2016** [comment]
Here is the colored AL "About" page. I slightly modified the content, is that okay?

Also do we want the "feedback" content on the page since it's already in the footer?

![image](https://user-images.githubusercontent.com/20231649/126537971-03baebcd-c718-4a5b-8694-74ef51438526.png)

**Comment by nonprofittechy** [comment]
This is best handled in ALToolbox.

**Comment by plocket** [comment]
Do we want to transfer the issue to that repo?
