### ISSUE TITLE
Clarify on address screen that we don't always need a contact address--sometimes the mailing address would be separate

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AssemblyLine#161]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `your address`
Other information | 
Variable being sought | `users[0].address.address`
Package version | `playground`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Tester contact info | @BryceStevenWilley

The current language on address screens is:

> What is your address?

> Use an address where you can be contacted.

This is misleading when there's also a mailing address being asked for: you'd likely be contacted at the mailing address, and not at your home address. Not sure how to use different language if the mailing address isn't defined yet, or if we can tell it will be asked.

**Comment by nonprofittechy** [comment]
Good point. I'm not sure how to handle this ambiguity. In some forms, for example, there is only room for one address. We want it to be the user's contact address, especially during covid when they will not appear in court in person. We could add a flag, but that may not be very discoverable.

I think it may be better to just allow the author to customize this question in that situation. See https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/359 which would make this a lot easier for the interview author
