### ISSUE TITLE
Add Google-style docstrings for all classes and methods

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#178]
Follow the specification here: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

- [ ] al_courts.py
- [ ] al_document.py
- [ ] al_general.py

**Comment by BryceStevenWilley** [comment]
Considering reopenning this, given the success of https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/issues/302. I'm generally afraid of long-term trying to keep the specific arguments and all of their uses in manual documentation, away from the code. Closer to code leads to it being less of a maintaince burden when we add args and such to the code.

I've also got a solid example of converting our current docstrings to Google style. This is what the params section (the only part that would really change with a switch to Google style) looks like now:

```
    @param up_action {string} - the variable name of an event to be executed on the server if the
        thumbs up is pressed
    @param down_action {string} - the variable name of an event to be executed on the server i
        the thumbs down is pressed
    @param (optional) review_action {string} - the variable name of an event to be execute on the
        server when someone submits their text review
    @param (optional) thumbs_display {string} - text displayed to user describing the thumbs
    @param (optional) review_display {string} - text displayed to user describing the text input
    @param (optional) submit_review_button {string} - text on the button to submit their text review
    @param (optional) post_review_display {string} - text displayed to user after review is
        submitted
    @returns the HTML string of the widget
 ```
 
 And would change to:
 
 ```
     Args:
        up_action (str): the variable name of an event to be executed on the server if the
            thumbs up is pressed
        down_action: the variable name of an event to be executed on the server if the
            thumbs down is pressed
        review_action: the variable name of an event to be execute on the
            server when someone submits their text review
        thumbs_display: text displayed to user describing the thumbs
        review_display: text displayed to user describing the text input
        submit_review_button: text on the button to submit their text review
        post_review_display: text displayed to user after review is submitted
    Returns:
        the HTML string of the widget
 ```
 
 No bad IMO, we just need to get used to writing things like that.

**Comment by BryceStevenWilley** [comment]
A confusing docstring to keep in mind when doing this refactor: https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/321#discussion_r1110010191
