### ISSUE TITLE
Allow downloading a single PDF of the combined bundle, possibly on the same row that the ZIP download option will appear

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#184]

**Comment by plocket** [comment]
It may be a good time to think again about making some more granular functionality accessible. For example, if someone had a need for a more configured row, we could give them access to making an individual row and then access to wrapping rows in our table. There's a lot of configuring folks could do on their own as their needs arise.

**Comment by nonprofittechy** [comment]
I'm not totally opposed to this, but I think choosing a table format is already very opinionated. I don't want to make this flexible to meet use cases we do not actually have, especially if CSS would be sufficient customization. Someone can always build their own download format with the .enabled_documents() method. Something in between the two formats might be hard to make useful. Flexibility imposes its own maintenance burden and requires more complex interfaces.
