### ISSUE TITLE
Add a way to set "enabled" status of a document on a per-bundle basis?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#191]
Currently, whether a file is enabled or not is set at the document level. That is: a document is enabled in every bundle at once. It could be useful to control the enabled/disabled status at a per-bundle level instead.

This should be optional, but it could be useful when there are multiple bundles.

It's probably solvable with object aliases on the attachment level, too. So may not be worth adding.

**Comment by nonprofittechy** [comment]
We can wait until someone actually requests this feature.

**Comment by BryceStevenWilley** [comment]
The current workaround would be just to duplicate the ALDocument, right? That doesn't seem too bad, at least if we can fix the speed issues.

**Comment by nonprofittechy** [comment]
Agreed, having an extra ALDocument that ultimately points to the same attachment block is enough of a solution here.
