### ISSUE TITLE
`index: invalid name al_doc_email_al_user_bundle` if there's a page after document bundles

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#192]
**Describe the bug**
I get the system error `index: invalid name al_doc_email_al_user_bundle`
When I use the `al_question_test.yml` and add a screen after the download bundles screen

**To Reproduce**
1. On the dev server, pull the `192_name_error_demo branch` (https://github.com/SuffolkLITLab/docassemble-AssemblyLine/compare/192_name_error_demo)
2. Start the `al_question_test.yml` interview
3. Get to the downloads screen
4. Hit 'Next'
5. See the system error on the screen
6. The browser console shows two things that seem unusual, though I haven't been able to diagnose the problem with them:
   1. `Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.`
   2. `POST https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12AL189DocZip%3Aal_question_test.yml 501 (NOT IMPLEMENTED)`
6. I couldn't find anything strange in the logs

**Expected behavior**
Go on to the next page

**Screenshots**

**Version Information (should be in `your.docassemble.server/updatepackage`:**
 - Docassemble Version: 1.2.74
 - AssemblyLine Version: 2.0.19

**Additional context**
`al_doc_email_al_user_bundle` is, I believe, the string created as the `id` for the email input field. I don't see where it's being used as something like a variable/key/attribute name. I've traced it to these locations that seem relevant to its journey:
- https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/al_document.py#L798-L804
- https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/data/static/aldocument.js

**Comment by nonprofittechy** [comment]
Seems pretty straightforward. The email input is being treated as a Docassemble input, and Docassemble is trying to process the name to define a variable, but the name is not base64 encoded.

I think we either need to put the email button in its own form, disable the "next" button from submitting the form with JS, or something similar to prevent it from getting to the server when you click "next"

**Comment by nonprofittechy** [comment]
relevant, on line 6053 of server.py

```python
    for orig_key in post_data:
        if orig_key in ('_checkboxes', '_empties', '_ml_info', '_back_one', '_files', '_files_inline', '_question_name', '_the_image', '_save_as', '_success', '_datatypes', '_event', '_visible', '_tracker', '_track_location', '_varnames', '_next_action', '_next_action_to_set', 'ajax', 'json', 'informed', 'csrf_token', '_action', '_order_changes', '', '_collect', '_collect_delete', '_list_collect_list', '_null_question') or orig_key.startswith('_ignore'):
            continue
        data = post_data[orig_key]
        try:
            key = myb64unquote(orig_key)
        except:
            raise DAError("index: invalid name " + str(orig_key))
        if key.startswith('_field_'):
            continue
```

perhaps starting with `_field_` and base64 encoding the name will make it valid. but we'll need to base64 decode in our JavaScript code which is a bit annoying.

**Comment by nonprofittechy** [comment]
Per Jonathan on Slack: we can add `_ignore` to the field name to tell Docassemble not to process it. It won't need to be base64 encoded.
