### ISSUE TITLE
Add an "email to x" button feature?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#194]
Use cases that I have encountered in just the last month:

* Email to a tenant organizer
* Email to City Hall / Board of Health
* Email to DESE

We have an "email to court" button, but abstracting it one level up might be useful.

**Comment by nonprofittechy** [comment]
This would be distinct from the send_button_html feature because it should:

1. Have the email hidden? if not hidden, at least pre-filled to something other than the user's email address.
2. Only allow interaction with once.
3. Change visibly when the sending succeeds.

**Comment by nonprofittechy** [comment]
@plocket this looks up your alley? I still think this is a good idea, although it's not urgent and I realize you're busy with other things at the moment.

**Comment by plocket** [comment]
Unfortunately, I do think I've got a bit much on my plate right now to get started on this anytime soon. If someone else wants to take it on, I'm happy to consult.
