### ISSUE TITLE
DOCX download link should use custom filename, not `file.docx`

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#195]
This might require changes in the attachment block, but if we can find a performant way to avoid that it would be better.

**Comment by nonprofittechy** [comment]
when you choose format="docx" in download_list_html, the DOCX files do not have a unique filename.

**Comment by nonprofittechy** [comment]
I think solution might be to have the `filename` set in the attachment block. But this is redundant to the ALDocument block. Could be confusing to maintain information in two places.

Alternative: we could look into other ways to control the filename. Can it be set manually on the DAFileCollection object--does that control the download's filename?

**Comment by purplesky2016** [comment]
> docx_concatenate() takes an optional keyword parameter filename, which, if provided, will be used as the name of the resulting file. If no filename is provided, the file will be named file.docx.

So if we use `docx_concatenate()` to generate the DOCX download, it should be able to get the real file name from the ALDocument block.
