### ISSUE TITLE
Investigate whether using muPDF will speed up PDF concatenation

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#198]
https://mupdf.com/docs/manual-mutool-merge.html

muPDF is supposed to be much faster than pdftk

**Comment by BryceStevenWilley** [comment]
Haven't tested muPDF's speed, but after I used [pikepdf to speed up bates numbering upstream](https://github.com/jhpyle/docassemble/pull/595), Jonathan [replaced much of pdftk with pikepdf](https://github.com/jhpyle/docassemble/commit/cb72a453e24942871dc24331cfde5ad5fceac71e), I think he mentioned that it was a bit of a speed improvement.

Still should keep this issue open until we actually test muPDF, but it's possible that the improvement will be a lot less now.

**Comment by nonprofittechy** [comment]
I suspect mupdf in particular isn't what we need to improve the speed of assembly. But agreed we can still think about it. Will keep this linked to #238 which is still open and more general ideas for speedup
