### ISSUE TITLE
Check on email subject and filename of doc sent through email

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#203]
Not sure if this is an artifact of how we wrote our al_question_test.yml, but the subject I got when I hit 'Send' was `Your "None" document from Suffolk Lit Lab is ready` and the name of the file was `user_bundle.pdf`. I'll look more deeply into it later, just adding this issue before I forget.

**Comment by nonprofittechy** [comment]
This has been documented and improved in https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/351
