### ISSUE TITLE
The "view" button returns a DOCX if you have a static file that is a DOCX

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#206]
It should be converted to a PDF instead.

Similarly, for the "download" button, it should be a PDF unless the person chose file_format="DOCX"

**Comment by purplesky2016** [comment]
What do you mean by "a static file"?

I tested an interview with a DOCX template that has only one field plus a DOCX attachment, the view button for both returned a PDF as expected. The attachment was with then without a field, both time it behaved the same way. 

The download button returned a zip of 2 PDF files.
