### ISSUE TITLE
Some way to differentiate between the person/people who's filling out the form and the individuals listed on the form (often the main party/parties)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#21]
Example: A form where the person filling out the information could be the filer themselves or an attorney.

We need to also be able to identify who's using the form. It affects things like:
- Where to say 'you' vs. a name
- Which fields a name should go in

Are we looking for a new variable to use? Are we looking to add a role to the different individuals in the interview? This wasn't initially standardized, but most of the current forms treat `users` as the person who is listed on the form as the main party (not sure of that wording legally), so we can't use that.

What I've understood of our thinking so far:
1. We're going to try to phase out `users` and start using `user_parties` instead
1. We will not re-use `users` so that old interviews will remain stable

## `set_info`
We are looking into using https://docassemble.org/docs/functions.html#set_info:
```py
set_info(user=user_parties[0])
#or
set_info(user=attorneys[0])
```

### Pros
1. It's already used in docassemble to help frame questions correctly, so it will have an added use (e.g., saying "you" on certain screens where we say the person's full name instead now).
1. It's a stable variable that you can poll and that exists regardless of which Individual objects you initialized in the interview. That makes it simpler to check than scanning all of the potential `Individual` objects to see which one have the flag set on them.
1. You can store these as objects instead of trying to juggle docassemble intrinsic names.
1. It's an existing, albeit slightly obscure convention.

### Cons
1. It's slightly obscure.
1. It's different than how we do other things currently

### Outstanding questions
1. Can this be used in a template? If so, how? Jonathan designed this to be part of multi-user interviews where two people participate at different times. 

## A flag
I assume an attribute such as `.types` on the `Individual`

### Pros
1. It's a syntax we've used before

### Cons
1. Whenever we need this piece of information, it requires scanning all of the potential `Individual` objects to see which ones have the flag set on them

## Some other state object

I _think_ this is what one version might look like:
```yml
---
code: |
  if is_attorney:
    state['attorney'] = 'users[0]'
    state['plaintiff'] = 'plaintiffs[0]'
  else:
    state['attorney'] = 'attorneys[0]'
    state['plaintiff'] = 'users[0]'
---
"plaintiff_name": ${ showifdef( value( state['plaintiff'] ) }
```

### Pros
1. It's a syntax we've used before

### Cons
1. It would lose the built-in advantages the `set_info` object has
1. It might need to be done in each individual interview, bringing more opportunities for mistakes
1. The particular method shown requires going through extra boilerplate code to be able to trigger the right intrinsic names

**Comment by plocket** [comment]
Let me know if folks think this should be here or in its own issue: Implement `main_party` or `user_party` (sorry, can't find the post on which one). For example, change `user_role` to `main_parties_role` etc. It'll need work in the weaver as well, of course.

I think the list for what needs to be created is short, but feel free to correct whatever needs correcting. I'll use `z` to mark where the correct new word would be added.
- [ ] `z_parties` in AL
- [ ] `z_parties` in Weaver
- [ ] `z_parties_role` in AL
- [ ] `z_parties_role` in Weaver

**Comment by plocket** [comment]
Also, what is the milestone for this one?

**Comment by nonprofittechy** [comment]
We kind of settled on `using_parties` or `user_parties`. But I'm trying to decide if it's worth the disruption now to rename `users`

**Comment by nonprofittechy** [comment]
I guess this is mostly duplicated in #109. But I think that one has a smaller scope. Maybe we should separate this into the two different issues-renaming variables and making the questions themselves more responsive.

Renaming the variables doesn't quite feel necessary, although it might make things less confusing for new developers.

**Comment by nonprofittechy** [comment]
Looking back over old issues, and while this was an interesting idea, not worth the disruption at this point. We could always revisit.
