### ISSUE TITLE
Identify a variable/flag to tell AL that the interview is available in multiple languages, and the list of languages

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#218]
This probably goes in the interview_metadata object?

Benefits of metadata key: you can configure in each individual interview. Drawback: more complex to decide which interview's translation status controls. We may not want to show any translated text unless the umbrella interview is fully translated (users can find it confusing to read partially translated content).

Maybe we don't use the `interview_metadata` key, but just the regular `metadata` block?

**Comment by nonprofittechy** [comment]
`interview_languages` : e.g., `['es','en']`
`interview_is_multilingual` `True` or `False`

Also use `AL_DEFAULT_LANGUAGE`

**Comment by nonprofittechy** [comment]
@BryceStevenWilley  @plocket thoughts welcome...esp. whether it makes sense to have this be an `interview_metadata` key or not. We've not been using that for very much but this feels like the right purpose for that object.

**Comment by nonprofittechy** [comment]
Purplesky points out that this raises a general question about how we want to handle one interview being overridden by another umbrella interview. How do we signal which setting takes priority?

**Comment by nonprofittechy** [comment]
Also see @BryceStevenWilley's issue here: https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/453

We may want to align this new use.

**Comment by BryceStevenWilley** [comment]
I tried looking at the metadata block recently, and I couldn't figure out how to access it programmatically (either in the python, or from the Jason dump), I've been leaning towards adding things to the `interview_metadata` dict recently.  

And I like the languages array, we can probably safely assume if it's not present, the interview is in English

**Comment by plocket** [comment]
It does seem like a good use for `interview_metadata`. Would that give us a good way to differentiate umbrella data? If that's declared in the `main order` block and only the topmost interview has a `main order` block, then there isn't a conflict? If not, maybe the global vars would be better as the umbrella interview could override those values pretty easily.

Quick question: Why would we want both `interview_languages` and `interview_is_multilingual` (or their equivalents)? Doesn't the number of languages tell us that? One less variable to update may be worth it.

**Comment by BryceStevenWilley** [comment]
> Why would we want both interview_languages and interview_is_multilingual (or their equivalents)? Doesn't the number of languages tell us that? One less variable to update may be worth it.

+1 there, don't think we need both. 

I'm not sure what you're talking about overriding `interview_metadata`  though: the point of `interview_metadata` is that you don't need to override it, each umbrella interview gets it's own interview metadata key. We do need to add a separate key to determine which interview is the main one (https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/453, which is the issue I think you're talking about?). But overall we don't need to handle conflicts between different `interview_order` blocks. The consumer might need to do some logic, i.e. the allowed languages of a form is the set intersection of its supported languages, but I don't think that should be a manual step.
