### ISSUE TITLE
Some courts trigger an unexpected screen when asking about courts

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#224]
**Describe the bug**
* Entering a valid MA address and setting `'allowed courts'` to `['Boston Municipal Court']` gets the screen `id: Tell us about a court`.
* Using just `'Appeal Courts'` or just `'Massachusetts Supreme Judicial Court'` gets the screen `id: Tell us about a court`.
* Using `'Massachusetts Supreme Judicial Court'` in combination with a court other than these gets the screen `id: Tell us about a court`.

We saw this in https://github.com/SuffolkLITLab/docassemble-Interpreternotice and we replicated it in https://github.com/SuffolkLITLab/docassemble-PetitionToChangeNameMinorCJP25 when we added the address question to the interview order.

**To Reproduce**
1. Set the allowed courts to the described court
1. Fill in a valid address
2. Get to the question asking about courts

**Expected behavior**
See a screen `id: choose a court (courts matching provided address were found)`

**Screenshots**
I can add screenshots if something is unclear, but I'm not sure how they'd help at the moment

**Version Information (should be in `your.docassemble.server/updatepackage`:**
 - Docassemble Version: 1.2.82
 - AssemblyLine Version: 2.1.2

**Additional context**
@stevejaubz is also familiar with this issue.

**Comment by nonprofittechy** [comment]
This is the full list of allowed courts: (SJC is not on it--neither is "Appeal Courts" but that might have been a typo?)

https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/macourts.py#L352

Was the address in Boston? Only Boston is served by the Boston Municipal Court.

**Comment by nonprofittechy** [comment]
When I only have "Boston Municipal Court" as an allowed court and I enter an address in Cambridge, I get this selector:

![image](https://user-images.githubusercontent.com/7645641/124018867-55b2f980-d9b6-11eb-9e21-5cf3ba676e3b.png)

That is with docassemble.MACourts 0.0.58.2. I notice that the dev server has docassemble.MACourts 0.0.58.

Can you see if the problem is still there once you upgrade?

**Comment by stevejaubz** [comment]
After updating I'm getting the right court selector - I see the `id: choose a court (courts matching provided address were found)` map with a real address in Cambridge and Allston,  and see `id: choose a court (no matching courts found` when I input a fake address that does not exist 

As far as the courts that are typo/ do not exist in allowed_courts (Appeal Court and Massachusetts Supreme Judicial Court)... I compared to the original yml from the Weaver and it looks like they were manually added - not a bug in the Weaver. 

I'll make a separate issue specific to the form to make this presentable for the SJC level/ make a warning. 

All set. Thanks.
