### ISSUE TITLE
Tester feedback: bug

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-AssemblyLine#225]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `reason for missing`
Steps to reproduce | id: reason for missing 
1. No selection for why did you miss your hearing 
2. Continues forward
Expected behavior | Require an input
What happened instead | Moves forward without a selection
Other information | 
Variable being sought | `reason_for_missing`
Package version | `playground`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | stevejaubz

**Comment by nonprofittechy** [comment]
@stevejaubz can you transfer to the right repo? (this is the default when you test from the playground)

**Comment by stevejaubz** [comment]
My b! Meant as a note for myself
