### ISSUE TITLE
Discuss when we review variable names for adjustment

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#230]
A lot of times when we write new code we play it fast and loose with variable and attribute names, but I don't think we stop and assess whether they can be improved to reduce confusion. Once they're in the code and start getting used, it's hard to improve them. One option for things like methods is to be backwards compatible. `foo.new_name = foo.old_name`. That's not possible all the time, though, so it might be good to have a procedure for a variable name review before releasing into the wild.

**Comment by nonprofittechy** [comment]
This is a good point but I don't think it's an actionable issue. Let's keep this in mind for PRs. Maybe add this to our style guide.
