### ISSUE TITLE
Consider providing a list of entered contact methods

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#231]
Came up against someone needing to state the existing contact methods, but in a way that wasn't addressed by what we'd decided would be the returned text. If they could have easily gotten back a list of the contact methods that had values, it would have been very convenient.

**Comment by nonprofittechy** [comment]
Alternatively, would using a template for the response be helpful? that way people could customize the text easily.

**Comment by plocket** [comment]
I like it - a template would mean people wouldn't have to figure out the logic from scratch and that's the core of the issue.

**Comment by nonprofittechy** [comment]
I think redundant with the fix in 01c8745f007aa424ba4b6eca54752052169d5936 but I'll mark it as "potentially revisit"

**Comment by plocket** [comment]
I'm not sure that fix provides the necessary flexibility, but seems ok to put this on `revisit` for now as it hasn't come up again.
