### ISSUE TITLE
Display title in mobile view

### ISSUE THREAD

**Issue by purplesky2016** [SuffolkLITLab/docassemble-AssemblyLine#239]
Currently the interview's title is hidden in mobile view. This seems to be an effort to make room for the dropdown menu in the header.

If we shrink the title's font-size, we can still display it while leave enough room for the menu.

**Comment by purplesky2016** [comment]
Current version:
![image](https://user-images.githubusercontent.com/20231649/125685431-6351a848-2f31-4495-a9bb-1afedc5c8f01.png)

If display in full size:
![image](https://user-images.githubusercontent.com/20231649/125685554-477ba859-6c6b-4309-b6ab-f431b17a8b03.png)

If display in shrunken size:
![image](https://user-images.githubusercontent.com/20231649/125685377-09b9b511-4703-4395-8238-a53db2613d9b.png)

**Comment by BryceStevenWilley** [comment]
Can we choose to hide the logo instead of having to make the title smaller? If we can make that choice it'd probably be a bit better, otherwise the smaller title is okay.

**Comment by purplesky2016** [comment]
How about this - it's in full size but without being "bold":
![image](https://user-images.githubusercontent.com/20231649/125961483-528fb8e9-d35f-4da5-a81f-2a621ad7ef9f.png)

**Comment by nonprofittechy** [comment]
We now hide the "undo" button as of #304, so I'm going to close this for now.

**Comment by purplesky2016** [comment]
But I've found the solution. I'm going to make 2 PRs, one for AL, one for massacess.

**Comment by purplesky2016** [comment]
Tried to push my change to a new branch, received this:

```
Error
create_playground_package: error running git clone.  Doing GIT_SSH=/tmp/datempm2fsn955.sh git clone git@github.com:SuffolkLITLab/docassemble-AssemblyLine.git
Cloning into 'docassemble-AssemblyLine'...
Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


```
