### ISSUE TITLE
Review what functionalities should go in what packages

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#241]
I think this is something we agreed would be good to do every now and then. I think there are some good candidates at the moment. For example, the mako-translation interview could do well in the toolbox or in AL and the feedback form is something I'd love to have in the toolbox.

**Comment by nonprofittechy** [comment]
This is a good idea but it doesn't really fit as an issue. Can we close and add to agenda for a Monday meeting instead?
