### ISSUE TITLE
Tests: Add MVP cucumber tests interview and feature files for the document classes

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#245]
Files to create: `test_aldocument.yml`, `test_aldocument.feature`

[Also very simple template files]

**Comment by nonprofittechy** [comment]
Will leave to you @plocket to decide if this issue can be closed after #251

**Comment by plocket** [comment]
Thanks! There are notes in the PR itself about certain improvements that can be made to what's there, and we might make future issues about adding specific tests. Renaming and closing this for MVP.
