### ISSUE TITLE
Feedback from Appeal Form: Overview map wanted

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#260]
From this bit of feedback: https://github.com/SuffolkLITLab/docassemble-AppealsCivilDocketingStatement/issues/21#issue-956957478

> it would be helpful to offer the full and complete form in blank so user either can download and print that to complete manually or with other applications, OR, so user can see where the form Q&A is heading and know what is being requested so they give best answers

1. Are we linking to the original form in the About page yet / should we? 
2. Some sort of overview map might make sense? Progress bar doesn't really fit for what this person wants. I feel we could make this feature with the DA navigation stuff, but it's not super clear if that would be enough. 

Far future, it would be cool to do a Docassemble look ahead: where you can see all of the possible next screens, in some sort of DAG. But that's much more than we need here, just thought it was a cool idea.

**Comment by nonprofittechy** [comment]
I think adding navigation is the best fix--almost every interview should have it.

A faster fix is adding the original form to the about page. We already have interview metadata for it, so I think we should roll that out gradually.

**Comment by nonprofittechy** [comment]
Going to close once #647 is merged as the main thrust of this issue-adding section labels--has to be done at the Weaver stage or on a per-interview basis.

**Comment by BryceStevenWilley** [comment]
Makes sense. We do have a lack of organization for improving existing interviews though: what would be the best place for a tracking issue for adding navigation to existing interviews?

**Comment by nonprofittechy** [comment]
This is still a good place for tracking issues for now, as we don't have too many of those to sort through here yet, but do we have a current plan for adding navigation to existing interviews? As nice as it is, I don't think it's an urgent task. It's more of a recommendation for ongoing maintenance and improvements that we triage. The longest interviews already have it. It's a step on our maturity model. And this issue feels too vague to be a tracking issue.

If we want to prioritize it, it needs to be more actionable first. E.g., with a list of the sections, a model interview, and instructions for a student to follow. We don't need the open issue here to know that having navigation is useful.
