### ISSUE TITLE
Make address fields dynamic, based on the selected country for the address field, handle international addresses

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#281]
MVP: update the "states list" if someone selects a country outside of the US. Also update the label of "zip code" to "postal code"

Beyond MVP: figure out which countries we can have country-specific address fields for, and which countries might benefit instead from just an open text input. We could probably just hardcode a small list of fields for countries that our client population frequently encounters, such as Canada and Mexico, although we might also consider using all of the fields that Google knows about and using a Python library that helps figure out which fields are relevant in a particular country. See https://docassemble.org/docs/objects.html#Address

```
    myaddress.street_number - the street number (e.g., 123).
    myaddress.street - the street name (e.g., Main St).
    myaddress.city - the city (known as (locality).
    myaddress.county - the county (known as administrative_area_level_2).
    myaddress.state - the state (known as administrative_area_level_1).
    myaddress.zip - the Zip code (known as postal_code).
    myaddress.country - the country (e.g., US) in ISO 3166-1 alpha-2 format.
    myaddress.administrative_area_level_1
    myaddress.administrative_area_level_2
    myaddress.administrative_area_level_3
    myaddress.administrative_area_level_4
    myaddress.administrative_area_level_5
    myaddress.colloquial_area
    myaddress.floor
    myaddress.intersection
    myaddress.locality
    myaddress.neighborhood
    myaddress.post_box
    myaddress.postal_code
    myaddress.postal_code_prefix
    myaddress.postal_code_suffix
    myaddress.postal_town
    myaddress.premise
    myaddress.room
    myaddress.route
    myaddress.sublocality
    myaddress.sublocality_level_1
    myaddress.sublocality_level_2
    myaddress.sublocality_level_3
    myaddress.sublocality_level_4
    myaddress.sublocality_level_5
    myaddress.subpremise
```

See #127, and also the way that the "state" field is made dynamic when someone selects a country in https://github.com/SuffolkLITLab/docassemble-ALWeaver/pull/478/files

**Comment by nonprofittechy** [comment]
Some code related to this that I'm removing from its original branch for now: 

```
        # if show_country:
        #     state_field = {
        #         "label": (f"% if not defined('{ self.attr_name('country') }'):\n" +
        #                   str(self.state_label) + "\n" +
        #                   f"% elif safe_subdivision_type({ self.attr_name('country')}):\n" +
        #                   f"${{ safe_subdivision_type({ self.attr_name('country')}) }}\n" +
        #                   "% else:\n" +
        #                   str(self.state_label) + "\n" +
        #                   "% endif"),
        #         "field": self.attr_name("state"),
        #         "default": default_state if default_state else ''
        #     }
        #     # TODO: futureproofing for dynamic state list
        #     # state_field["code"] = f"safe_states_list(country_code={self.attr_name('country')}) if pycountry.subdivisions.get(country_code={self.attr_name('country')}) else ()"

        #     fields.append(state_field)
```

**Comment by nonprofittechy** [comment]
There is a recipe for this now, albeit in a weird place: https://docassemble.org/docs/background.html#background_response_choices

**Comment by BryceStevenWilley** [comment]
Started working on this, got some initial experiments working in [`international_addresses`](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/new/international_addresses).

Notes on what I still need to work on:

* We should default to showing the full state/province name for countries that aren't the US. I don't think that the state codes from pycountry are commonly used in addresses. For example, in Mozambique, example addresses that I can find include the full state name:
    * https://www.usaid.gov/mozambique at the bottom
* It seems that there's something wrong with the recipe, specifically with `showifdef(..., prior=True)` for objects / attributes. I have a patch, but it needs a bit more testing.
* Still need to test how things are handled with Google Autocomplete when choosing the country on the screen

**Comment by BryceStevenWilley** [comment]
Worked on this some more today, updates in the comment above; I'm still a bit skeptical that the approach of the state dropdown for every country is the best UI, as fancy as it is. I'm leaning towards just making an optional text field state input for countries that aren't the US, which avoids the remaining two problems mentioned, and depending on the country, should be enough information. Google autocomplete should still fill in the state's name if present, and if it's not present, I'm not sure that it's necessary for a physical or mailing address, and would prefer to let users who know their country better than us fill it in.
