### ISSUE TITLE
Add a method on ALAddress to show the long form of the state/province/sublocality

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#296]

**Comment by nonprofittechy** [comment]
this would just be a wrapper to state_name() with country_code specified, as a convenience

**Comment by BryceStevenWilley** [comment]
This never made it into main, and the changes are still on https://github.com/SuffolkLITLab/docassemble-AssemblyLine/compare/address-field-enhancements. Reopening.
