### ISSUE TITLE
Allow downloading ALDocumentBundle as a .ZIP file

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#31]
The "download" button for an ALDocumentBundle should have an option of downloading as a .ZIP file when there is more than one attachment in the bundle.

**Comment by plocket** [comment]
Should this be added as a third button in the same row as the document (next to 'View' and 'Download') or should it have its own row?

**Comment by nonprofittechy** [comment]
It should only happen if there are multiple files (but most new forms will have at least a next steps document).

It will be a final row of the table
