### ISSUE TITLE
Use the "next" button with radio buttons for yes/no questions, not "yes/no" buttons

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#316]
T&P 26-1

Comment was that the "yes/no" immediate effect isn't consistent on different screens, which might be especially disorienting for someone w/ a screen reader. We had similar feedback from Bentley and voted against making the change, mostly because we felt the ease of use of a button (fewer clicks on mobile) outweighed the inconsistent UX. @CaroRob had some thoughts on this.

Opening issue for now--we might decide two votes is enough, or we might close after making the note here.

**Comment by BryceStevenWilley** [comment]
Wanted to mention that I'm specifically for making things more consistent and using `yesnoradio` when possible. I tested it with a screen reader, and for the Orca screen reader on Ubuntu + firefox, this is what is read for each:

* yesno top level: "press one of the following buttons yes push button, no push button"
* yesnoradios in fields: "choices yes not selected radio button no not selected radio button" (or "selected radio button" if the user selects one of the radios), "press one of the following buttons continue push button"

The latter is definitely much better for a screen reader. While the first might be okay depending on how far through the interview they are ("press one of the following buttons" is the aria text for every continue button, so it might be clear to the user that these will continue the interview), but that's a really narrow place to allow that type of question, that we can't actually control where authors put yesno top level questions.

I changed all of the buttons in AL core in the `603_tp_wcag` branch that I'm about to make into a PR.
