### ISSUE TITLE
Meta: Remove banner help button

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#318]
T&P 37

**Comment by nonprofittechy** [comment]
If we don't use question help button or overall interview help, this actually never appears. So it's not critical to address this--it would require an upstream fix.

**Comment by BryceStevenWilley** [comment]
We don't use the help button just in this package. I do believe it's pretty present in our other interview packages. Github's exact search is horrible, but there are at least a few in [this search](https://github.com/search?l=YAML&p=5&q=org%3ASuffolkLITLab+%22help%3A+%7C%22&type=Code).

**Comment by nonprofittechy** [comment]
Now that the upstream `question help` button doesn't add anything to the banner and it shows up below the "next" button I don't think this fix is needed anymore.
