### ISSUE TITLE
Remove question-level help buttons and replace with "collapse_template" button

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#321]
T&P 73, 74-1, 74-2, 75

We only have a few stock questions that use the help button now.

**Comment by BryceStevenWilley** [comment]
Some further clarification from the T&P feedback on why the Help button isn't a great choice:
![Screenshot from 2021-10-20 12-42-27](https://user-images.githubusercontent.com/6252212/138137314-b096f670-6621-4194-b09c-d4a9906b405e.png)
