### ISSUE TITLE
Create some wrapper code to help developers remind users of important dates to return/follow-up on next steps

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#333]
https://github.com/SuffolkLITLab/EfileProxyServer/issues/1

Create reminders

Use cases:

A legal process has a beginning, middle and end but the Docassemble interview might only help someone with one part of the process. Reminders can help users complete the full legal process even if the interview itself can't complete every step.

1. Come back and file your form
2. Did the opposing party (or the court/forum) do the thing they were supposed to do?
    - Did you get the paperwork you asked for
3. You are about to hit a deadline for some action triggered by what you did in our interview. Take your next step
4. You started the interview and got to a screen asking you to come back later--come back later!

Could think of this mostly as a series of "next step" links to other interviews on the server.

**Comment by BryceStevenWilley** [comment]
An existing one off way of implementing this is in MADE: https://github.com/GBLS/docassemble-MAEvictionDefense/blob/main/docassemble/MAEvictionDefense/data/questions/eviction.cron.yml

**Comment by nonprofittechy** [comment]
How can the user stop reminders if they want to opt out? Should that be in every reminder?

**Comment by BryceStevenWilley** [comment]
I found [a good playbook with some best practices for reminder texts](https://uploads-ssl.webflow.com/63345e33f3c909d27d0e558b/6378176932502b9187567968_xdjin2F7laMqVGy2mgM4pVkQSkNr5oHF7OYwZ5oksCQ.pdf) that we could link in the documentation when this feature is in and documented.
