### ISSUE TITLE
Empty button in the audio playback button

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#336]
Getting an accessibility error on the WAVE AIM checker that says our audio playback button is an empty button.

Hopefully an easy fix?

**Comment by plocket** [comment]
FYI, references for this are things like the video `aria-label` in the code at https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Video_and_audio_APIs and https://www.w3.org/TR/wai-aria-practices-1.1/#no_aria_better_bad_aria.
