### ISSUE TITLE
Remove instantces of "Court Forms Online" from this package

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#346]
There are 3 main places where the phrase "Court Forms Online" appears in this repo:
* the [basic questions intro screen](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/543814f26d59db8aada69d81f322b669fadc7184/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L28-L33)
* the [sharing email/sms templates](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/543814f26d59db8aada69d81f322b669fadc7184/docassemble/AssemblyLine/data/questions/al_visual.yml#L239-L249)
* the [share form screen](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/543814f26d59db8aada69d81f322b669fadc7184/docassemble/AssemblyLine/data/questions/al_visual.yml#L163-L171), less critical since they're just default messages that the interview user can change

They're really small places, and technically can be overridden, but it's difficult to find where there are until you see them, and in general AL should be more agnostic, and these blocks can be moved as-is to [MassAccess](https://github.com/SuffolkLITLab/docassemble-MassAccess).

The open questions here that I'd need to answer before doing more with this are:
* do we all agree that we should remove "Court Forms Online" in general?
* what's a better, more generic, default to replace with "Court Forms Online", for the out-of-the-box AL interviews. I would using something like `get_config("servername")`, but it doesn't seem quite right. Maybe just "Online forms"?
* do we want to replace the phrase with something "hard coded", i.e. written in the files just like Court Forms Online is now, or do we think that a Server-wide config is a better choice (with a still hard coded fall back)?

**Comment by nonprofittechy** [comment]
Very timely! Just to make a choice to go along with #345, I'm going to add a new variable: `AL_ORGANIZATION_TITLE` which will default to the value of `get_config('appname')`. We should directly use the value of `AL_ORGANIZATION_TITLE`.

**Comment by nonprofittechy** [comment]
Also thinking we should do the same with links to courtformsonline.org

**Comment by BryceStevenWilley** [comment]
Makes sense! I'll use the `AL_ORGANIZATION_TITLE` (might make the default `AL_ORGANIZATION_TITLE` be 'Court Forms Online', and either remove the spaces to make the title that you changed in https://github.com/SuffolkLITLab/docassemble-AssemblyLine/commit/1cd6bbe3109c3c2bda756ff6acb843c6921f14b0 or just put spaces in that title, given we use 'Court Forms Online', not 'CourtFormsOnline' in full sentences and such. 

I'll also make an `AL_ORGANIZATION_HOMEPAGE` that can default to `get_config('external host')` (wrong config name, but you get the idea).
