### ISSUE TITLE
Duplicate Basic Info / Acknowledged Inform Pages

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#347]
There's a question at https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/851cf6ae2e52ffab137e8042b5c289015e305931/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L25-L78, and another at https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/851cf6ae2e52ffab137e8042b5c289015e305931/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L813-L863 that are _almost_ identical. They are different only in that:

* the higher one has an id of `basic questions intro screen`=
* the higher one uses `The CourtFormsOnline Project can help you ...` instead of `This website`
* the higher one has a `continue button field: al_intro_screen`, and the bottom doesn't
* the higher one includes "This site is not a lawyer..." disclaimer and link to LSC legal aid finder.

The former is the one trigger more often, given the continue button field, but the bottom one would be triggered if anyone ever specially tried to set `acknowledged_information_use` before the info screen. Either way, we should get rid of the redundancy, but I'd prefer to not make decisions about content.

**Comment by nonprofittechy** [comment]
We don't have any interviews that directly reference acknowledged_information_use before the info screen, so I think we can safely remove the second version of the question. Good catch.
