### ISSUE TITLE
Fix `id: is the user the plaintiff or defendant?` expandable help text is in the title

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#354]
Couldn't find this in another issue. In the `id: is the user the plaintiff or defendant?` question, the title includes the text 'How do I know', which can expand to show the explanation. It's all the same size as the header, though.
<img width="592" alt="help_in_header" src="https://user-images.githubusercontent.com/52798256/147490196-7fd26c1d-fd27-480d-908d-90648044fae6.png">

It's intended for the body of the question, right?

**Comment by nonprofittechy** [comment]
I think this is fixed already

**Comment by plocket** [comment]
My bad, was on the PR branch and didn't realize `main` had been updated separately.
