### ISSUE TITLE
Make PDF generation optional in download_list_html

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#367]
It should be possible to speed up file download in an interview that only generates DOCX files by removing the PDF generation completely. This should be a small fix--impacting some current users of the ALDocument code.

**Comment by nonprofittechy** [comment]
Never mind! This already is optional==`download_list_html(format="docx", view=False, include_zip=False)`

**Comment by calvinkeller3** [comment]
Thanks!
