### ISSUE TITLE
Weirdness with variables persisting across sessions

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#393]
We have noticed a little weirdness around Docassemble sessions that may be one issue or multiple unrelated issues.

1. Sometimes after editing code in the playground that doesn't trigger a server restart, the code still didn't update. This was happening when testing the save snapshot feature in AssemblyLine. Might have been a problem with `all_variables()` accessing the wrong memory location after pickling.
2. @plocket has been running into issue when testing ALWeaver locally where the second run of a test has a different list of recognized "people" variables than the first run of the same test with the same input file. We have noticed a reproducible issue when you use the back button, but it feels like the way @plocket triggers the test shouldn't act the same as using the back button. Maybe we need to fix the `process_people_variables()` function to not modify the object in place and that would fix the issue.
3. I vaguely remember running into issue where after I did a new "Save and run" some of the information was pre-filled in (like file uploads?) even though the interview questions weren't pre-answered. (Now I'm wondering if this is caused specifically by the file number reuse bug with Docassemble?)
4. @BryceStevenWilley said this rang a bell for him too, but he didn't have specific details on our call yet.

Want to use this thread to gather related anecdotes so we can see if there's anything we can reproduce.

**Comment by plocket** [comment]
On the Playground in the testing server: I may have just found that the particular problem I found may not even be associated with the browser. As a preliminary confirmation, I ran the weaver in Chrome incognito window, closed the window, and opened another one to run it again, getting the field to disappear the second time. I then ran the weaver in Safari (which I haven't opened for years) and, tellingly, the field still wasn't there.

The interview wasn't running in any other browser tabs at the time. That was the only tab. The Playground for it was open in Chrome.

**Comment by plocket** [comment]
Replication with package installed on server, using civil docketing statement, as I have for all of this:
1. In Chrome, I installed the weaver package on the test server
2. In Safari, I went through the interview once, selecting `decision_maker` as a person.
3. Closed the window, quit Safari.
4. Re-opened Safari and went to the interview again. It started on the first page.
5. Got to the "custom persons" screen again and the `decision_maker` option was missing.

**Comment by nonprofittechy** [comment]
@plocket what do you mean when you say you "went to the interview"? What link did you use? What parameters did it have? Was it an incognito window?

**Comment by plocket** [comment]
> what do you mean when you say you "went to the interview"? What link did you use? What parameters did it have?

The interview of the package installed on the server, as you describe in your docs: https://apps-test.suffolklitlab.org/run/ALWeaver/assembly_line

> Was it an incognito window?

Not for the package installed on the server itself. It was just a browser I don't use and has never logged into the test server as a user of any kind. It's worth trying. I do want to note that, as I described, the behavior still happened with the Playground interview when I was in incognito windows.

> For the playground interview, similar question--did you use the "run" button or save and run?

I didn't use either. I just used the url: https://apps-test.suffolklitlab.org/interview?i=docassemble.playground40alweaverDissapearingOptionManualTest%3Aassembly_line.yml. Again, I used it in one incognito window, then I closed the window in that incognito mode (that was the only incognito window I had open), opened a new incognito mode window, and ran it it from the link again. You do need to close all the incognito windows or the current incognito window has some kind of state tracking.

How about this - leave me instructions for exactly what needs to be done so I don't waste time guessing and trying random combinations.

**Comment by nonprofittechy** [comment]
The `run` in the url should be `start` otherwise it does not create a new session. Same with just revisiting a url. You need either `start` or `new_session=1` to make a new session.

**Comment by plocket** [comment]
I have now used `reset=1` and got the same result as before. I have a vid and the variables.

**Comment by nonprofittechy** [comment]
Okay, thanks, that's good data. I do want to see if this is fixed by making the `process_people_variables` no longer modify the list in-place--not sure if I can understand the nexus, but it is the most distinct thing about that specific issue.

**Comment by nonprofittechy** [comment]
I'm now sure this was specific to ALWeaver and it was an example of why you should never use a mutable default parameter.

**Comment by BryceStevenWilley** [comment]
Just so their linked, https://github.com/SuffolkLITLab/docassemble-ALWeaver/pull/761 is the fix that was in the Weaver. I think the issue was less a mutable default parameter and more about module level variables, though both should be avoided.
