### ISSUE TITLE
Add blank space under collapse_template()

### ISSUE THREAD

**Issue by mnewsted** [SuffolkLITLab/docassemble-AssemblyLine#400]
You may already know this, but I see that the text window that appears when a template is shown does not have very much space between it and the lines/fields below (see screenshot). Does there need to be a different default margin or padding on the card (if that's the right thing to ask)?
![image](https://user-images.githubusercontent.com/66691956/153689720-4435743a-feb3-4957-9086-aba56bad431e.png)

I was able to address this by adding the following css (thanks MB!), but I don't know if this will cause issues elsewhere. Please let me know if you have any questions. Thanks!

.collapse.show {
    margin-bottom: 1rem;
}

**Comment by nonprofittechy** [comment]
That's a good suggestion. We can add it to the default css

**Comment by mnewsted** [comment]
Thanks @nonprofittechy ! 
I forgot to add that my solution causes the expand scroll to hiccup. It looks like it slides open then adds the margin. I can demo if you like. I'd love to figure out a way to make it smooth.

**Comment by purplesky2016** [comment]
@mnewsted - to fix your rule just remove `.show` 

```
.collapse {
     margin-bottom: 1rem;
}
```
I'll be working on the template functions so I'll add this rule to ALToolbox which will fix `AssemblyLine`

**Comment by mnewsted** [comment]
Thanks! So I should remove the following after ALToolbox/AssemblyLine is updated? It's still only in dev, so I have time.

.collapse.show {
    margin-bottom: 1rem;
}

**Comment by purplesky2016** [comment]
Yes. It may take a couple of weeks for us to update though.

**Comment by mnewsted** [comment]
Thanks! I'll keep it in until then. I appreciate the help!
