### ISSUE TITLE
Support PDF-A export if the document is signed

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#402]
Gives both the users and the courts a little more assurance that the PDF hasn't been edited after having been signed.

Also, could debate wading into "actual" digital signing with certificates, etc. Python has the libraries for sure (early versions of https://github.com/SuffolkLITLab/docassemble-EFSPIntegration used certificate signing to communicate with Tyler).

**Comment by nonprofittechy** [comment]
I think it's a worthwhile feature to add even if it's not required by state regulations. It's a question we've heard asked about a few times now.

**Comment by BryceStevenWilley** [comment]
Took a quick shot at this tonight, thinking it would be easy. It isn't super hard to pass around the `pdfa` parameter that gets passed to `pdf_concatenate`, but I ran into issues when I tried to verify that the output PDF was actually PDF/A. I think those should be fixed upstream by https://github.com/jhpyle/docassemble/pull/528, but I'll wait for it to be merged before trying this again.
