### ISSUE TITLE
Add a "service_address" attribute to an ALIndividual

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#413]

**Comment by BryceStevenWilley** [comment]
Minor: to prevent issues where `has_service_address` is set, but `service_address` isn't, and vice versa, can `has_service_address` just be a [`@property`](https://pythonguide.readthedocs.io/en/latest/python/property.html#property)?

**Comment by nonprofittechy** [comment]
I don't think so--the idea would be a variable that asks someone if they have a different address where they would like to be served. Most people won't have that address. But another pattern which might be better is to use object assignment with a `disable others` like we do for the mailing_address attribute
