### ISSUE TITLE
Simplify and provide models for gathering custom attributes when gathering items in an ALPeopleList

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#414]
E.g., a version for "with birthdates" to gather children, a version "with mailing address" for mailing addresses, etc.

We could easily create these as `generic object` blocks so people can just quickly pull in with the `.using(`

**Comment by nonprofittechy** [comment]
From deep dive discussion, these might be helpful as sample blocks in ALRecipes. But a different feature would be more helpful:


Have a new syntax, like “complete_attribute_list” that accepted a list of attribute names as parameters
`- users: ALPeopleList.using(complete_attribute_list=[“name.first”, “birthdate”, “employer_name”])`

* This doesn’t let you use conditional logic in the complete block.
* It’s adding a new syntax that works in limited circumstances which can confuse people
* There’s a risk people would use this as another place to put logic. E.g., they could add an attribute to the list that itself is defined by a code block
    * Downside there: the logic will be more complicated to trace

**Comment by BryceStevenWilley** [comment]
Update: the `complete_attribute` as a list of strings to be completed has been added to Docassemble 1.3.25: https://github.com/jhpyle/docassemble/commit/a350f9a6f94057fd9c90dad9da20cdf35f667d7e

**Comment by nonprofittechy** [comment]
Good catch, thanks @BryceStevenWilley. I also started some sample code in ALRecipes
