### ISSUE TITLE
Have an end-user ready feature to re-use information in multiple interviews

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#421]
It should be possible for an end user, on a single server, to have something like a "save/load" system for "answer sets". The existing Docassemble sessions are created and deleted transparently and they are tied to a single interview. Answer sets are cross-interview and they are intentionally managed.

This would let an attorney have something like an intake interview and then generate multiple documents with the same basic client details. They should be able to easily change the name of the "saved answer" to match their client's name. We could also have some smart defaults for the saved name. This would also let someone without an attorney, like a petitioner in a family law case, fill in multiple forms that preserve the information about the case. Some cases have many optional motions or related pleadings where the same data would carry over.

This system will only work when the variables are shared across both interviews. For the AssemblyLine, we have a pretty good shared vocabulary of fields, so we have a head start there.

There are a lot of "variables" that we don't ever want to copy into a new session. We need a way to allow/blocklist those. There are also some common attributes of objects that we don't want to copy because they just clutter up the session or might be stale--things like the field labels when people use `name_fields()` method.

Because someone might want to copy data into an interview that we just didn't plan for, it's important that they have some way to edit the responses that they gave **or** maybe to "skip" the answers that they already gave. A "good" interview will have a review screen, but we should probably not **rely** on having a review screen. Ideally when someone "loads" an answer set, they go straight to that review screen. See #419. Sometimes we may also have very simple form-filling interviews where we let Docassemble auto-generate questions.  

Someone should have a simple interface that allows them to delete answers and rename them. Saving should also use a simple menu system.

Answer sets would be designed for "cases", not "people". That is, someone might want to have the same information on multiple forms in the same "case", but use a variation of it for a different "case". Separate from the idea of answer sets is the concept of a user profile system with unchanging data about the user. See #418. User profile data can be used for default values. Answer sets should only be used when the user makes an explicit choice to do so.

**Comment by nonprofittechy** [comment]
The implementation of this feature can build on our current developer-only snapshot feature. Here is how snapshots work:

1. In the running session, someone clicks the "save snapshot" button
2. They give the session a name and click the "next" button
3. Behind the scenes, we copy the data into a dedicated "interview" which is just a container for the answers. This container interview can have its own server-wide rules set for preserving data.

When someone wants to restore the session:

1. We display all sessions on the server for that user. The ones that are from this dedicated container interview are prefixed with the name of the container interview.
2. Someone selects the session they want AND the name of the interview that they want to copy the data into. 
3. Behind the scenes, we copy the data from the container interview into a new session of the selected interview.

Some thoughts on how we can refine this experience now:

1. Stop showing the name of the interview with the list of sessions.
2. Stop showing the sessions that weren't explicitly saved in this list. That will give people a more curated list of sessions to explore and make it easier to identify the session that they want to use.

Missing features:

1. Rename
2. Delete
3. Edit answers

**Comment by nonprofittechy** [comment]
For performance reasons, we can't rely on Docassemble's native feature to display the interview title. It's too slow. We might want to save the interview's title into a dedicated column.

**Comment by nonprofittechy** [comment]
![image](https://user-images.githubusercontent.com/7645641/160444188-284f568d-70b3-4468-bec8-20faea1f6324.png)

**Comment by nonprofittechy** [comment]
Think about how to distinguish between:

- resuming a session
- copying saved answers into a new session of the current interview

**Comment by nonprofittechy** [comment]
Maybe a link to "in progress forms"

**Comment by nonprofittechy** [comment]
Feedback from @plocket : the "edit" pencil which I intended to mean "rename answers" implied editing the actual answers. We probably don't have a way to let someone edit the actual answers yet.

https://thenounproject.com/icon/rename-498552/

is a nice icon that more clearly indicates renaming (although still somewhat ambiguous). Is there any equivalent icon in fontawesome?

**Comment by plocket** [comment]
Closest I could find (some not very close):
* [Input pipe](https://fontawesome.com/icons/input-pipe?s=solid)
* [Input text](https://fontawesome.com/icons/input-text?s=solid)
* [Cursor](https://fontawesome.com/icons/i-cursor?s=solid)
* [Pen field](https://fontawesome.com/icons/pen-field?s=solid)
* [Keyboard](https://fontawesome.com/icons/keyboard?s=solid)

**Comment by plocket** [comment]
Someone suggested more info to add about the saved interview, but that would be pretty crowded. If we want more info, collapsable content might be a way to do it.

**Comment by nonprofittechy** [comment]
Maybe use the "auto fill" label

**Comment by nonprofittechy** [comment]
Ideas about names:

- port
- reuse

**Comment by nonprofittechy** [comment]
People may want to add their own metadata to the answer set. They might want a preview of the answers. They might want the ability to edit the existing answers.

**Comment by nonprofittechy** [comment]
Probably can delete the session people load into if there aren't very many screens that have answers provided.
