### ISSUE TITLE
Create a simpler class / set of questions for ALExhibitDocument

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#427]
ALExhibitDocument has features like:

- cover page
- auto-numbering
- individual document titles
- multiple pages and multiple documents

That don't always make sense. Many interviews have a single file that they want the user to upload, like a court notice, where the title is known in advance.

We just want a simple wrapper around an upload to use there that lets you drop the uploaded file into an `ALDocumentBundle`. Maybe call the class `DAUploadedFile`?

**Comment by BryceStevenWilley** [comment]
I like the idea a lot. My only addition is the possibility of making it more than one file, still known beforehand what it'll be. Say, user needs both a W-9 and scan / picture of an id card. It'd still make sense for that to be the same document (both relating to I-9s), but helps to have separate inputs.

**Comment by nonprofittechy** [comment]
> I like the idea a lot. My only addition is the possibility of making it more than one file, still known beforehand what it'll be. Say, user needs both a W-9 and scan / picture of an id card. It'd still make sense for that to be the same document (both relating to I-9s), but helps to have separate inputs.

I was thinking one upload, one DAUploadedFile, but you could collect multiple DAUploadedFiles into a bundle. Would that work for the use case you describe?

**Comment by BryceStevenWilley** [comment]
You're right, that would work fine. It feels a little unwieldy, if you still wanted each of those uploaded files to still be one document, having to put them in a separate bundle. But it's probably more confusing having multiple places to bundle things.

**Comment by nonprofittechy** [comment]
Someone could still use a `datatype: files` for that

**Comment by nonprofittechy** [comment]
I take that back: supporting multiple files of mixed types in an upload is pretty complex. It will be easier to support just one file upload per `ALDocumentUpload`
