### ISSUE TITLE
Age formatting for children under 1

### ISSUE THREAD

**Issue by amandaleighbrown** [SuffolkLITLab/docassemble-AssemblyLine#449]
**Describe the bug**
When using .age_in_years, for list members under 1 year of age, the age shows 0. Can it show months? With that, it may be helpful to automatically note in the produced data itself whether it's months or years (to avoid inaccurate text in a template.

**Comment by nonprofittechy** [comment]
Hi @amandaleighbrown -- check out the `formatted_age()` method. I think that does what you want.

https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/algeneral#ALIndividual and https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/7133887be128cd0c3f151e823174f5badd1ff864/docassemble/AssemblyLine/al_general.py#L429
