### ISSUE TITLE
`al_logo.alt_text` isn't defined in a backwards compatible way

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#466]
Error

    Interview has an error. There was a reference to a variable 'al_logo.alt_text' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.

**Comment by BryceStevenWilley** [comment]
Is this a session issue? Uggghhh. I probably won't be able to reproduce. The alt_text is is just [this objects block](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/93a235df5f40678831a1b8a0a9dcef4e82a5a87e/docassemble/AssemblyLine/data/questions/al_visual.yml#L3), is there a way for docassemble to only redefine an object block when it can't find an attribute? I don't want it to have to recreate the image on each page load.

**Comment by nonprofittechy** [comment]
I think we just need this code block:

```
code: |
  al_logo.alt_text = "Assembly Line Logo"
```
