### ISSUE TITLE
De-duplicate the feedback form footer

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#48]
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/c9607e1b5cfedda7e5877ef33bdabbffe64ad5bb/docassemble/AssemblyLine/data/questions/al_visual.yml#L49-L53

Both `if get_config('debug'):` and its `else:` seem to use the same code. If that's correct, we can get rid of the `if`.

**Comment by nonprofittechy** [comment]
They do. In MAVC, those went to separate places, which was a limit of Google Forms. I think there's no reason to use two separate forms anymore.

**Comment by nonprofittechy** [comment]
I think this is a useful place to suggest that we move the feedback form into this repository, and update the links accordingly. I'm updating the issue title to match the broader scope.

**Comment by nonprofittechy** [comment]
We actually decided to add a footer to every page with a "feedback" link. #137
