### ISSUE TITLE
User: part of the form was confusing (ported from AffidavitofIndigencyMAVC)

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#56]
Original link: https://github.com/SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC/issues/14

&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `email status`
What was confusing | I wasn’t able to edit the “Enclosed:” portion of the cover page and I believe that this makes my request look less professional.
Other information | 
Variable being sought | `email_status`
Package version | `0.0.17`

**Comment by BryceStevenWilley** [comment]
This is relevant to https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/46/files#diff-4cdfc9b29601a618ed5992dd96a70f4fa19ad4b6c0133ed30f2bed9a584e3903R89. I understand the sentiment, but not sure I understand why it makes them seem less professional, or what they would add to make it more professional. 

I guess it's worth it to possibly add an enclosed text entry, pre-populated with the `download_titles` variable.

**Comment by plocket** [comment]
Was this issue filed by a developer or by a user hoping to edit the resulting document?

**Comment by BryceStevenWilley** [comment]
`¯\_(ツ)_/¯`  good question, I had assumed that it was a user, but it could have been a developer. Do issues that are created from the test server look different from prod? I can't tell which the original issue is from.

**Comment by nonprofittechy** [comment]
Helpful feedback, but we discussed this quite a lot over the summer. The cover page is not meant to be editable by an end-user, other than the "other information for clerk" box that they can use to provide instructions.
