### ISSUE TITLE
.does_verb() does not match capitalization of parameter

### ISSUE THREAD

**Issue by ianeis** [SuffolkLITLab/docassemble-AssemblyLine#582]
For example, `Now {{ users.does_verb(‘Come’) }}` in a .docx template outputs `Now come/comes`.

This is inconsistent with .as_noun() which does match case.

`.did_verb()` may also have this issue. Have not tested.

**Comment by ianeis** [comment]
For now there's a manual workaround with `.capitalize()`

**Comment by nonprofittechy** [comment]
This is upstream in https://github.com/jhpyle/docassemble/ but I'll see if I can make a pull request to fix it

**Comment by nonprofittechy** [comment]
Closing since this isn't appropriate to fix in this repo. Best we can do is a workaround or get it merged upstream.
