### ISSUE TITLE
Change labels of the name questions from "First name", "Middle name" etc to "First"?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#589]
https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/issues/237

In a user test session, user typed their full name into the "First name" field. Possibly because they saw "Name" closest to the label.

**Comment by ianeis** [comment]
Seems like a harmless change to me. I think most people are used to seeing "First... Middle... Last" and assume they're referring to names -- except maybe for Middle Name which may be confused for Middle Initial.

**Comment by nonprofittechy** [comment]
Like #588, this probably needs more testing. Going to close with a chance to revisit--more testing of #588 should reveal whether this fix is appropriate or now.

A better fix might also be to use horizontal layout of fields, but that may break on mobile.
