### ISSUE TITLE
Create a question for serving an opposing party

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#597]
The purpose would be to help complete a certificate of service. It should let someone specify if they are going to serve the opposing party in hand, by email, etc., as well as whether they are serving in person or by their attorney.

It should be possible to specify the service method for each opposing party.

**Comment by BryceStevenWilley** [comment]
Linking an older issue, https://github.com/SuffolkLITLab/docassemble-MassAppealsCourt/issues/6. I moved it there because I'm not sure if AL core is the right place; how much does it vary by jurisdiction? likely that Appeals specifically isn't the right place either.

**Comment by nonprofittechy** [comment]
I think it's not going to vary too much by jurisdiction actually. Maybe we make a separate variable for the list of allowed methods of service but otherwise it should be almost identical in most states.

It's definitely a more specific question than we've had in the baseline up until now but I think it's the kind of thing that will really add value.
