### ISSUE TITLE
Fix visual appearance of review screens

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#60]
Right now, the "Edit" button is styled `float: right` which makes it very far away from the text you are editing. `float: left` with a `margin-right: 1em` looks a bit better, but if the text is multi-line the margin shifts to the left which is a bit weird.

![image](https://user-images.githubusercontent.com/7645641/111875888-78268700-8972-11eb-96f3-598d0b412aec.png)

I suspect someone can play around with this and make it better than it is now.

**Comment by nonprofittechy** [comment]
There may be other fixes...another option is highlighting the row that the edit button will act on on button hover (not mobile friendly), or adding visible border around the row that is always enabled.

**Comment by purplesky2016** [comment]
Could you provide a url of a short interview that can reproduce your screenshot? I would like to download it and play with the Edit button.

I don't have a good test interview. When I tried to run `al_question_test.yml`, I got an error `AttributeError: module 'docassemble.base.functions' has no attribute 'set_task_counter'`. The version number is 2.0.12, commit 681d389.

**Comment by BryceStevenWilley** [comment]
Note that we're closer to the desired product from fresh Weaver interviews than I think their "observation" interview was. 

This is the output for people variables that the weaver recognizes. The edit button takes you to a separate page with the full table of info for them. Maybe we want to show users more info on the review screen there. 
![Screenshot from 2021-10-20 11-32-28](https://user-images.githubusercontent.com/6252212/138124550-eddbc1d9-ff63-4ddf-823c-8ffb4b90e431.png)

![Screenshot from 2021-10-20 11-32-37](https://user-images.githubusercontent.com/6252212/138124554-d89a0fd7-94e0-4cae-bc69-2621dce84934.png)

**Comment by nonprofittechy** [comment]
There were some good upstream changes that address this. Closing for now.
