### ISSUE TITLE
When using `save_interview_answers()` it should be possible to set the answers to encrypted/unencrypted

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#625]
Currently, we remove `multi_user` from the answers. Probably, it should be an explicit interview author choice whether or not to encrypt the answer set that doesn't depend on the encryption settings of the source interview.

**Comment by nonprofittechy** [comment]
Also note we can add a `multi_user: True` to the answer set destination interview.

**Comment by BryceStevenWilley** [comment]
What are some of the benefits of this change? I know currently existing sessions get shared to legal aid helpers, multi-signature stuff, etc., but my impression was that answer sets were primarily supposed to be for the one person filling it out; encrypting answer sets seems like a good choice there. 

Is this about making sure `multi_user = True` when things are loaded back into an interview?
