### ISSUE TITLE
`courts` is deprecated but we should consider handling it here

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#63]
https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/314

One possible solution is to just make it a list with one item--trial_court

**Comment by nonprofittechy** [comment]
I think we should make this work in the main AssemblyLine repo, not just in ALMassachusetts. So that probably means making `courts` a DAList instead of a DAEmpty.

**Comment by plocket** [comment]
In that PR, it is a DAList. `courts[0]` is then set to `trial_court`. Is there something else that needs to be changed?

**Comment by nonprofittechy** [comment]
Something yes--may need more investigation. My memory is this did not work out of the box when you run a new form through the weaver yet after mering #66. I may need to confirm that is where the remaining problem was.

**Comment by nonprofittechy** [comment]
I tested again and I must have been wrong about the bug. It's still acting a little weirdly with a new Weaver run of this file: 
[Uploading Housing Temporary Restraining Order.pdf…]()
