### ISSUE TITLE
Urgent: SQL statements need to be upgraded to SQLAlchemy 2.0 syntax

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#658]
See: https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection.execute

Specifically, we have a lot of connection.execute() statements in session.py (maybe somewhere else too?) which use named parameters to fill-in the Text() object's parameterized SQL statement. In SQL ALchemy 2.0, you can pass a positional parameter which is a single dictionary but you cannot pass several named parameters.

To check: whether the new 2.0 syntax is also compatible with 1.4 (I think it is).

**Comment by nonprofittechy** [comment]
It hopefully is as easy as changing statements like this:

```python
    with db.connect() as con:
        rs = con.execute(
            get_sessions_query,
            metadata=metadata_key_name,
            user_id=user_id,
            filename=filename,
            limit=limit,
            offset=offset,
            filenames_to_exclude=tuple(filenames_to_exclude),
            exclude_newly_started_sessions=exclude_newly_started_sessions,
        )
```

To look like this instead:

```python
    with db.connect() as con:
        rs = con.execute(
            get_sessions_query, {
              "metadata": metadata_key_name,
              "user_id": user_id,
              "filename": filename,
              "limit": limit,
              "offset": offset,
              "filenames_to_exclude": tuple(filenames_to_exclude),
              "exclude_newly_started_sessions": exclude_newly_started_sessions,
            }
        )
```

**Comment by BryceStevenWilley** [comment]
I'll tackle other AL repos outside this one (currently testing a patch for the Dashboard); I can also handle this one for you if you want, just let me know.

**Comment by BryceStevenWilley** [comment]
Another note: By default, SQL Alchemy's rows are [now named tuple](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Row), without "mapping" behavior. So code like `row["filename"]` should be turned into `row.filename`.  We can also change it to [something like `row._mapping["filename"]`](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.RowMapping), but given we already have to change things, the cleaner change is probably preferable.

**Comment by BryceStevenWilley** [comment]
Apps-dev is still on 1.4.32, one version before DA did the SQL Alchemy upgrade, so I'll test things there to make sure they work. I think you're right that these changes should work on SQL Alchemy 1.4, it seems like a lot of things were deprecated, but to see which were it [required you to set a particular env var](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings). Not sure how to best do that in docassemble, but I think in general, 1.4's new features are compatible with 2.0.

**Comment by BryceStevenWilley** [comment]
Only needed to update the Dashboard and AL core; tested Interview Stats and GithubFeedbackForm, and those work fine on SQLAlchemy 2.0 as well. Going to close this.
