### ISSUE TITLE
Check if we have or need a function to turn True/False/None into "yes/no/I don't know"

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#67]

**Comment by purplesky2016** [comment]
Jonathan has a yesno() function, it works like this:
${ yesno(True) } = "Yes", ${ yesno(False) } = "No".
noyes() works similarly. 

I didn't find a function that turns "None" to "I don't know." Do we need it?

**Comment by nonprofittechy** [comment]
We do have one-- yes_no_unknown() is in ALToolbox

**Comment by nonprofittechy** [comment]
I don't actually remember why I asked this question. But the function exists. Maybe this will help locate it 🤷
