### ISSUE TITLE
`ALDocument` `title` front end a bit cluttered

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-AssemblyLine#676]
Hard to see beginning and endings of titles. Other than the capital letter and looking to the buttons it’s really not distinguishable between one doc title to the next.

Full screen screenshots 
![Screen Shot 2023-04-12 at 11 05 19 AM](https://user-images.githubusercontent.com/65858862/231540265-53ea2e16-efcd-4850-ba3d-02add46e65f0.png)
![Screen Shot 2023-04-12 at 11 05 39 AM](https://user-images.githubusercontent.com/65858862/231540270-c47f5d95-0470-4f7a-a075-8a0ec916ad4e.png)

Non-full screen screenshots
![Screen Shot 2023-04-12 at 11 04 23 AM](https://user-images.githubusercontent.com/65858862/231540352-6b51dc57-9361-48ee-a145-7c9fc06ade6a.png)
![Screen Shot 2023-04-12 at 11 00 59 AM](https://user-images.githubusercontent.com/65858862/231540358-6c6f0175-42d7-421b-bcd6-244933a32572.png)

**Comment by BryceStevenWilley** [comment]
Can you try updating to the latest Assembly Line from GitHub on main? We haven't made a release since https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/594, which made a lot of improvements here, and there are a few things in other parts of the code we need to address before making another release.

**Comment by miabonardi** [comment]
> Can you try updating to the latest Assembly Line from GitHub on main? We haven't made a release since #594, which made a lot of improvements here, and there are a few things in other parts of the code we need to address before making another release.

Says I am running 2.21.0 which I think is current main?

**Comment by BryceStevenWilley** [comment]
We haven't bumped the version string, but we've made a few commits since 2.21.0 was released in early February. You can't know which exact commit it's on unless you just reinstall it from main.

**Comment by miabonardi** [comment]
I tried again and it still looks similar. Just noting it

![Screen Shot 2023-04-12 at 2 33 29 PM](https://user-images.githubusercontent.com/65858862/231552454-6ccb84f3-e81b-45fd-b89b-7e13f7d29fac.png)

**Comment by nonprofittechy** [comment]
A likely first fix is just adding a little top margin for each row

**Comment by plocket** [comment]
I think this must still be an old version somehow or you have some custom styles, as when I pull `main` in, My titles are bold and right aligned. You might have to avoid using the button to update and, instead, use the field at the top of the package management page to manually pull in the `main` branch. That said, even in our current version they don't have spacing between them. Made a PR in #678 for that.
