### ISSUE TITLE
Playback new UI does not show on a "help" page

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#68]
![image](https://user-images.githubusercontent.com/7645641/112849678-4b135c00-9077-11eb-9446-95ead166d759.png)

The unstyled HTML5 audio element displays on the help screen, even if the correct new UI appears on other pages of the interview.

**Comment by BryceStevenWilley** [comment]
Looking into this a little bit, the audio container does still have the proper CSS class (daaudio-control), but it doesn't seem like `daPageLoad` triggers when the help tab is triggered. We might be able to hook into this JS (server.py:7827 in docassemble)
```js
function daShowHelpTab(){
          $('#dahelptoggle').tab('show');
}
```

**Comment by plocket** [comment]
Was pointed to https://getbootstrap.com/docs/4.0/components/navs/#tab when looking for events to hook into.

**Comment by nonprofittechy** [comment]
The way I read Jonathan's comment, it looks like this HTML audio element is already on the screen:

![image](https://user-images.githubusercontent.com/7645641/113906032-cd033380-97a1-11eb-9a82-26e042009de5.png)

That implies we need the existing daPageLoad event, but need to modify both a visible and an invisible HTML 5 audio element.

**Comment by plocket** [comment]
Thanks for catching that. I think you're right. I can probably do that fairly quickly.
