### ISSUE TITLE
Where should `package_title` be defined, and to what?

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#71]
`package_title` is only used in the `general_cover_sheet.docx`, which is used in the send to court code. It isn't defined by the weaver at all however. 

It seems to be mostly related to MAVC, but it is defined in some older interviews, like https://github.com/SuffolkLITLab/docassemble-MAMotiontoVacateMaritalHome/blob/e663ac3bdbe35983d77527012fca9ad29359cc0e/docassemble/MAMotiontoVacateMaritalHome/data/questions/Motion%20to%20Vacate%20Marital%20Home.yml#L937.  If I had to guess, maybe it's only useful for multiple forms that are all in the same package, i.e. 209A? 

Shoud the instance in the cover sheet be removed, or should we have more documentation (and something generated in the weaver) for it instead?

**Comment by nonprofittechy** [comment]
>  If I had to guess, maybe it's only useful for multiple forms that are all in the same package, i.e. 209A?

Yes, I think that was the original thought. I agree that generating something for it in the Weaver is a good idea. `package_title` is generated as a placeholder by searching the first key in `interview_metadata` in the MAVC repo. We might not have copied that behavior over to AssemblyLine. That does feel like a reasonable shim for now.

Also see #13

**Comment by BryceStevenWilley** [comment]
Sounds good. I like the default shim in AL, and we can try to add it in the wizard after multiple attachments get in (https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/113).
