### ISSUE TITLE
Missing `sign-form-lineal.svg`

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#736]
Lots of logs on production that say: `File reference docassemble.AssemblyLine:sign-form-lineal.svg DID NOT EXIST.` Idk what could be going on

https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/ea9e2a08105265db6a93a25c40889ebc3da29d58/docassemble/AssemblyLine/data/questions/al_visual.yml#L195

**Comment by nonprofittechy** [comment]
I am familiar with this one--I think it's something in the github feedback form that's not causing any user-visible errors. but we should fix to make logs more readable.
