### ISSUE TITLE
Help make screenshots more distinctive: possibly create a function to output image w/ drop shadow

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#75]
It's common to use screenshots of documents to explain where to locate information on a paper form. When the image has no border or drop shadow, it looks weird and blends into the white background of the page.

We could either write a function to output w/ the drop shadow (it should accept either a string or a DAStaticFile--if the string, it should use `url_of('image.png')` or modify the CSS for all inserted images.

These are the CSS classes to modify: daimageref and/or dawideimage classes.

**Comment by nonprofittechy** [comment]
I'm leaning toward changing this style for all images for now. Any thoughts? I'll bring it up at next Tuesday management meeting.

**Comment by purplesky2016** [comment]
I tried [File] with css, here is one version:

**Original:**
![image](https://user-images.githubusercontent.com/20231649/114775749-a9ab2c00-9d3f-11eb-9dfd-1b9dba4e386e.png)

**With shadow and border-style:**
![image](https://user-images.githubusercontent.com/20231649/114775625-7f596e80-9d3f-11eb-95d3-d4060c461f14.png)

What do you think? We can play with the effects further if this is the direction to go.

**Comment by purplesky2016** [comment]
Here is another version
![image](https://user-images.githubusercontent.com/20231649/115879879-2319dd00-a418-11eb-98ff-21a34875cbbf.png)

**Comment by nonprofittechy** [comment]
We should also look into the built-in Bootstrap classes to add a drop shadow. That would make them responsive to Bootstrap themes. And we should do a quick `grep` through the @suffolklitlab repos to see if all of the places people currently use images would be OK to get a drop shadow.

See: https://getbootstrap.com/docs/4.1/utilities/shadows/

**Comment by purplesky2016** [comment]
Maybe I misunderstood. The built-in Bootstrap classes would require js changes, not css, right? E.g.
 `<div class="shadow-sm p-3 mb-5 bg-white rounded">Small shadow</div>`

That would not help existing interviews either.

**Comment by nonprofittechy** [comment]
That's a good question! I actually do not know the answer--any chance to add a CSS class dynamically without using JS?

**Comment by purplesky2016** [comment]
I doubt it. My understanding is that CSS is all about styling html elements, while class is used to define the html elements (hence JS).

**Comment by nonprofittechy** [comment]
I think you are right. Next question is whether we want to use JS to apply the bootstrap class or directly edit the relevant docassemble CSS classes; or to use a function to generate an IMG tag with the right CSS classes added.

**Comment by purplesky2016** [comment]
Do you really like the bootstrap shadow styles? They are quite limited it seems on the example page.

**Comment by nonprofittechy** [comment]
No. I am just wondering if it could make it easier for a different jurisdiction that uses a bootstrap theme if we stick with bootstrap classes. But that is not a very strong motivation

**Comment by nonprofittechy** [comment]
@plocket thinks there is a way to use Bootstrap variables w/o using the Bootstrap class. This could go in MassAccess too--but as long as Illinois and Louisiana are OK with it, maybe keep it here.

**Comment by plocket** [comment]
To clarify, if there's a Bootstrap variable for shadow color, we could use that to keep the shadow color consistent with the theme. That way it would be possible to have our shadow work with both a dark theme and a light theme.

This wouldn't implement the Bootstrap class, so it still adds complexity that may be hard for individual projects to wrangle later, but it would help maintain the accessibility features that Bootstrap does have.

**Comment by nonprofittechy** [comment]
Agreed--I think this looks ready for a PR @purplesky2016
