### ISSUE TITLE
Possible URL injection in feedback?

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#764]
Opening and then closing a rather strange bug, unlikely a security issue, but I was confused by it.

Got the following production error recently:

```
There was an error in the CourtFormsOnline application. The error message was:

ValueError: 

    ValueError: invalid literal for int() with base 10: 'ZD1kb3VwO2QuZHB1eXQuaHB5PTE7ZC5odHBrPUxvYWRpbmcuLi47aW1pY3U9'

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 6568, in index
    reset_interview = int(request.args.get('reset', 0))
ValueError: invalid literal for int() with base 10: 'ZD1kb3VwO2QuZHB1eXQuaHB5PTE7ZC5odHBrPUxvYWRpbmcuLi47aW1pY3U9'

The referer URL was https://apps.suffolklitlab.org/interview?reset=ZD1kb3VwO2QuZHB1eXQuaHB5PTE7ZC5odHBrPUxvYWRpbmcuLi47aW1pY3U9&i=docassemble.AssemblyLine:feedback.yml&github_repo=docassemble-CDCEvictionMoratorium&github_user=suffolklitlab&variable=warn_moratorium_ended&question_id=moratorium+has+ended&package_version=0.0.35&filename=docassemble.CDCEvictionMoratorium:data/questions/cdc_eviction_moratorium.yml&session_id=<redacted>&from_list=1

The external hostname was apps.suffolklitlab.org
```

The URL is clearly from someone clicking the feedback button that appears on the CDC Moratorium page. However, the strange part is `reset=ZD1k...`. That string is base64 for `d=doup;d.dpuyt.hpy=1;d.htpk=Loading...;imicu="`, which looks like it could be some sort of injection attack. It won't be able to do much, as reset only works when it's 0, 1, or 2, but it's concerning anyway. Either:

* there was some ability to inject things into URLs that we give people (https://github.com/SuffolkLITLab/docassemble-GithubFeedbackForm/blob/e643556f52990156c978785040c62f59ef4b3af7/docassemble/GithubFeedbackForm/github_issue.py#L116), unlikely though
* people are editing URLs to try to change our system somehow.

Not sure it's actionable, but I didn't want to record it publically, so it doesn't rot away in an email.

**Comment by nonprofittechy** [comment]
This looks like a pretty common random attack pattern to me. But this is a place we process URL args so it's good to check.
