### ISSUE TITLE
What is the purpose of children[i].name_fields()?

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine#780]
What is the purpose of [children[i].name_fields()](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/059565941969d3472b71b0e918c9912c4651a20a/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L831C7-L831C32) ?

I want to use the basic, easy-to-understand-and-follow docassemble way to ask for children's names and birthdates, but I cannot figure out how to get around AssemblyLine's interference in my interview. See [collecting_children_info_docassemble_way.yml](https://github.com/CaroRob/docassemble-CollectingChildrenWithAndWithoutQLBaseline/blob/main/docassemble/CollectingChildrenWithAndWithoutQLBaseline/data/questions/collecting_children_info_docassemble_way.yml)

The way Assembly ql_baseline.yml asks for children's names seems far too complex and yet cannot be avoided if we want to use the wealth of features AssemblyLline offers. sad face emoji [collecting_children_info_using_AL.yml](https://github.com/CaroRob/docassemble-CollectingChildrenWithAndWithoutQLBaseline/blob/main/docassemble/CollectingChildrenWithAndWithoutQLBaseline/data/questions/collecting_children_info_using_AL.yml)

**Comment by plocket** [comment]
I think the question is more about `.name_fileds()` than children.

**Comment by nonprofittechy** [comment]
It's definitely not required to use `name_fields()`, and it's only a small help for asking for the name of a person, when it's never a business name:


1. The up to 4 fields (title, first, middle, last, suffix)
2. Our built-in translations for those field labels

We have it mostly for consistency across the different interviews and avoid extra strings needing to get translated. It's awkward but I think the best way to achieve templates for questions without forcing people to re-translate field labels.
