### ISSUE TITLE
Can we have 1 children[i].name_field() question?

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-AssemblyLine#781]
It is difficult to understand and then overwrite these 2 so generic questions - I found it very confusing.
I didn't realize there are **2** questions that need to be used or overwritten. 
And the questions as they are in the code are difficult to understand. 
#780

**Comment by nonprofittechy** [comment]
Do you have suggested language?

**Comment by plocket** [comment]
I believe a suggestion was to get rid of the `childres[0]` question and have just one question, using Mako `% if` to show the different desired page titles. Something like PR #783.

This would avoid the confusion of needing to override two separate questions that look pretty similar.
