### ISSUE TITLE
Write an interview file for testing just benchmarks

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#80]
- [ ] Start with ALDocument behavior that uses files we store in 'Sources' and jumps straight to the download screen.

The hope is to implement the testing framework so it can handle benchmark type testing.

We can probably use the documents we currently have in 'Sources' and just assign values to the variables it needs. We want at least one addendum [and one Word document. Probably bump up the number of bundles or documents to do better stress testing].

**Comment by nonprofittechy** [comment]
This might actually exist as an MVP. Might only be in my playground folder.

**Comment by nonprofittechy** [comment]
In #238 we clarified there are multiple separate issues that cause slow assembly. I don't think this issue is needed.
