### ISSUE TITLE
Add the ability of the user to remove the copy/clone feature from the In progress documents screen.

### ISSUE THREAD

**Issue by ladracer** [SuffolkLITLab/docassemble-AssemblyLine#814]
![In progress documents 2](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/assets/40646388/35da28a6-b0a5-47f6-a56d-1e26f5a0d286)

Ultimately, to solve the issue in the interim, I saved my own version of sessions.py and then commented out lines of code 882-886. 

Perhaps surrounding that code in an if statement would be a simple solution.

**Comment by nonprofittechy** [comment]
Currently this depends on the global configuration setting for answer sets
