### ISSUE TITLE
Custom audio element continues playing when help button is pressed.

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#82]
If you press 'play' on the page and then press 'help', the initial audio element will continue playing. The reverse is also true. It should instead... pause? Reset? We'll go with pause for now as it's the least destructive and people can restart when they want.

I'm not sure which way of doing this would be the least fragile.

Side note: In describing this issue, I'm realizing the functionality of the 'stop' button (letting the user restart) is not really signposted very well. That's a bit of a bummer. Would be great to have a designer think about that.

**Comment by plocket** [comment]
So the 'help' and 'back to question' buttons don't trigger any special da events to lock onto to pause playback. Right now I see two main options:

1. Pause all audio when any button or link is pressed. The advantage is that most buttons are navigation buttons and that if the user is pressing on a button, they're probably otherwise occupied and it'd be useful to pause the audio. This will catch a lot of cases.
2. Pause audio based on the pressing of the 'help' and 'back to question' buttons specifically. This won't catch as many cases. Because of that, it will permit cases that we can't think of yet where tapping a button or link should not pause the screen reading.

Do folks have a preference?

**Comment by nonprofittechy** [comment]
Option 1 sounds good

**Comment by BryceStevenWilley** [comment]
Copied from #165:

> I guess I don't think that pausing on all clicks is useful, and would have suggested option 2 in #82 (comment). It's just a hunch, but we don't have any user feedback on it. Pausing on help and back makes sense, because there are completely different screens, but this also stops on help text on fields and green terms too.

**Comment by plocket** [comment]
I'm hearing we each have our gut instincts on what would be more or less helpful. I think A/B testing would be the logical next step at this point. We might make an issue for that by itself.
