### ISSUE TITLE
Support more old (MAVC) features where possible

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#85]
There's at least one I can think of, but feel free to add more if you've noticed them:
- [ ] `basic_questions_intro_screen`

**Comment by nonprofittechy** [comment]
Didn't actually mean to commit straight to main, but this is a safe fix. I think it could be better to add separate issues for each one we identify. We already have an issue to track migration questions - #69 so I suggest we make backwards compatibility issues for each TODO that we discover
