### ISSUE TITLE
Documentation issue - DOCX Templates in AssemblyLine

### ISSUE THREAD

**Issue by apstrom** [SuffolkLITLab/docassemble-AssemblyLine#869]
**Describe the bug**
Difficulty customizing templates in AssemblyLine.

**To Reproduce**
```
---
include:
  - docassemble.AssemblyLine:al_package.yml
---
mandatory: True
code: |
  tab_intro
  thumbnails_defaults
  download_list_defaults
  end_tab
---
objects:
  - exhibits_bundle_defaults_1: ALDocumentBundle.using(elements=[exhibit_doc_defaults_1], filename="exhibits_bundle_defaults", title="Exhibits with defaults")
  - exhibit_doc_defaults_1: ALExhibitDocument.using(title="Exhibits doc defaults", filename="exhibits_doc_defaults", include_exhibit_cover_pages="True" )
---
object: ALExhibit
attachment:
  variable name: x.cover_page
  docx template file: exhibit_cover_sheet_APS.docx
  field code:
    exhibit_label: raw(x.label)
---
object: ALExhibitDocument
attachment:
  variable name: x.table_of_contents
  docx template file: exhibit_table_of_contents_APS.docx
  field code:
    exhibits: raw(x.exhibits)
    include_exhibit_cover_pages: raw(x.include_exhibit_cover_pages)
---
field: tab_intro
mandatory: True
question: Tabbed document generator
subquestion: |
  This tabbed document generator creates a single PDF out of multiple documents. It will automatically insert a tab for each document and include a tab sheet in the generated PDF. It will also provide a table of contents for the PDF. [BR][BR]
  *Be careful to review the output PDF. This generator will only work as well as you input information. If any inconsistencies or misdescriptions exist, you must catch them and correct them.*
---
id: thumbnails_defaults
continue button field: thumbnails_defaults
question: Please review the compiled tabs.
subquestion: |  
  You will be able to download these documents in their final form on the next screen.[BR][BR]
  ${ exhibits_bundle_defaults_1.as_pdf() }
    
  ${ exhibits_bundle_defaults_1.as_zip() }
  [BR][BR]If changes are required, select the "undo" button.
---
id: download_list_defaults
continue button field: download_list_defaults
question: Download the completed document.
subquestion: |

  ${ exhibits_bundle_defaults_1.download_list_html() }
---
id: end_tab
event: end_tab
question: You have successfully compiled your documents into a single tabbed document.
buttons:
  - Restart: restart
---
```

**Expected behavior**
The templates specified in the object blocks for ALExhibit and ALExhibitDocument should be used in stead of the default templates. 

**Version Information (should be in `your.docassemble.server/updatepackage`:**
 - Docassemble Version: 1.4.111
 - AssemblyLine Version: 2.28.1

**Additional context**
This may be more of a documentation issue for those, like me, who do not have the technical skill to delve too deeply into Python. The few lines of text relating to changing template files in the documentation do not have enough detail for me to know which actions to take. 

I have uploaded my custom templates to Docassemble's template folder and to the template folder created in docassemble/AssemblyLine/data/templates. Neither upload is used. 

As I say, I am likely missing some code that points to the correct template. I cannot, however, discern enough from the below documentation to customize the template. 

> Customizing Exhibits
> You can add your own template for the table of contents by customizing your_document.cover_page. Use [the stock table of contents](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/data/templates/exhibit_table_of_contents.docx) template as a model. It has some fancy math to figure out what page number to start the exhibits at, based on whether it thinks the table of contents itself will spill onto a second page.
> 
> You can add your own template for the individual cover pages for each document, too. Use the [stock cover page template](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/data/templates/exhibit_table_of_contents.docx) as a model.

**Comment by nonprofittechy** [comment]
Hi apstrom, you've changed `generic object` in our code to `object` in your code which is what caused your problem. `object` isn't a Docassemble keyword. 

You don't need to use [`generic object`](https://docassemble.org/docs/modifiers.html#generic%20object) here--you can directly specify the attribute. `x` has a special meaning in Docassemble for generic object questions only. You'd substitute your actual document's name for the `x`.

```yaml
---
attachment:
  variable name: exhibit_doc_defaults_1.table_of_contents
  docx template file: exhibit_table_of_contents_APS.docx
  field code:
    exhibits: raw(exhibit_doc_defaults_1.exhibits)
    include_exhibit_cover_pages: raw(exhibit_doc_defaults_1.include_exhibit_cover_pages)
```

**Comment by apstrom** [comment]
Thanks!

Is this solution equally applicable to the exhibit cover page template?

**Comment by apstrom** [comment]
Still having an issue with the cover page template. DocAssemble is not pulling the correct template (from the DA templates folder, not AssemblyLine's folder). 

I am trying to swap the word "exhibit" in the cover page for "TAB", which allows ALExhibitDocument to be used for things like motion records or compendia. Whatever I do, the output returns the stock AssemblyLine cover page template.

This issue has been driving me nuts. Any help would be much appreciated.

My code: 

```
---
objects:
  - exhibits_bundle_defaults_1: ALDocumentBundle.using(elements=[exhibit_doc_defaults_1], filename="exhibits_bundle_defaults", title="Exhibits with defaults")
  - exhibit_doc_defaults_1: ALExhibitDocument.using(title="Exhibits doc defaults", filename="exhibits_doc_defaults", include_exhibit_cover_pages=True, include_table_of_contents=True,)
---
attachment:
  variable name: exhibit_doc_defaults_1.cover_page
  docx template file: exhibit_cover_sheet_APS.docx
  field code:
    exhibit_label: raw(exhibit_doc_defaults_1.label)
---
attachment:
  variable name: exhibit_doc_defaults_1.table_of_contents
  docx template file: exhibit_table_of_contents_APS.docx
  field code:
    exhibits: raw(exhibit_doc_defaults_1.exhibits)
    include_exhibit_cover_pages: raw(exhibit_doc_defaults_1.include_exhibit_cover_pages)
---
```
