### ISSUE TITLE
Language: Signature choice can be confusing when user is signer

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#91]
From @CaroRob's comment in https://github.com/SuffolkLITLab/docassemble-209aPlaintiffMotionToModify/issues/71

> ...unless we have a question at the beginning for an advocate to help a plaintiff, it is confusing to have the option to email the form to someone else to sign.
> 
> I already said I am the plaintiff at the beginning of the interview - why would I send this form to anyone else to sign?

My reply:
> I wonder if there's some kind of wording that could be more ambiguous but still work. Maybe like 'send the form to be signed on another device'?

Kate's reply:
> I think that suggestion is good. I like having the option of emailing just in case.

My reply:
> To clarify my meaning, you might not send it to be signed by someone else, but you might send it to yourself on a different device. The current problem with that wording is that it's passive voice. I'm not sure how to improve it.

**Comment by nonprofittechy** [comment]
I guess we could have more generic language here, like "gather signatures". OR a more clear way to share an interview with someone else.

**Comment by nonprofittechy** [comment]
This would partially be addressed by a dedicated "share" button on the bottom of every page.

**Comment by nonprofittechy** [comment]
@CaroRob what do you think?

**Comment by plocket** [comment]
That is, we would change the language on the signature page so that it addresses the user directly and the way for the user to send the signature to someone else would implicitly be the 'share' button.
