### ISSUE TITLE
Create a generic addendum that works for most interviews with reasonable defaults

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#94]
The generic addendum should include enough to be a typical addendum with some customization based on the form type.

E.g.:

1. A case caption with the name of the parties and court
2. The name of the form
3. The name of each field

It should also handle both tabular data, flat lists, and text-based overflow.

**Comment by nonprofittechy** [comment]
I'd welcome thoughts on this addendum format: [docx_addendum.docx](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/files/6329641/docx_addendum.docx)

**Comment by purplesky2016** [comment]
As a reference, `Addenda - extra table records.yml` and `Addenda - text too long for docx form.yml` in `ALToolbox ` seem to be related to what you are talking about.

**Comment by nonprofittechy** [comment]
See #97
