### ISSUE TITLE
Feature request: Make email "editable" forms optional for PDFs

### ISSUE THREAD

**Issue by mnewsted** [SuffolkLITLab/docassemble-AssemblyLine#98]
Currently, on download forms page, when requesting forms to be emailed, there is a checkbox to indicate that the user wants an editable copy of forms. For some of my programs, I don't want the user to have this option for when I am assembling PDF forms.

Can we let the developer choose whether to display the optional checkbox depending on the kind of forms we assemble?

Maybe we could do this as a parameter in the function that creates the checkbox.

**Comment by nonprofittechy** [comment]
Oops sorry @BryceStevenWilley I didn't notice you had self assigned.

**Comment by BryceStevenWilley** [comment]
All good, I hadn't done anything yet!
